### PR TITLE
feat: Read release body template from config

### PR DESCRIPTION
**Pull request by dominikschulz**
This PR makes it possible to override the relase notes template from the config to e.g. avoid the ugly footer.

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [x] I have read the **CONTRIBUTING** document.
* [ ] `make ci` passes on my machine.
* [x] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 2a5812bb36839780509c0827de32806afceb5dab
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by caarlos0** [comment]
> void the ugly footer.

didn't know it was ugly 🤔

Don't know if I like this though, we can maybe just remove the footer and then the user can pass anything with the `--release-notes` flag...

https://goreleaser.com/#release.custom_release_notes

**Comment by dominikschulz** [comment]
I'm sorry if my choice of words was misleading. Let's say we don't like the footer. I pretty much like this project and I'm happy to refer to it, but not in every release.

Passing release notes in with the `--release-notes` flag is nice, but this requires us to write release notes before. With this change, especially combined with #622, we're able to create pretty nice release notes without any additional work.

**Comment by caarlos0** [comment]
OK, no problem.

I think it is better to just remove the footer. Then the `--release-notes` flag can solve this problem pretty easily :)

**Comment by dominikschulz** [comment]
Ok, that would work as well.
I'll respect whatever you prefer, but is there a technical reason why you don't like this approach. IMHO it's very unobtrusive and clean.

**Comment by caarlos0** [comment]
> Ok, that would work as well.
> I'll respect whatever you prefer, but is there a technical reason why you don't like this approach. IMHO it's very unobtrusive and clean.

no technical reason at all, just want to keep things as clean as possible...

**Comment by caarlos0** [comment]
@dominikschulz check #624

**Pull request closed without merging**
