### PR TITLE
feat: Add support for using Gitlab Project ID instead of the owner/name combination, Fixes #1799

### LINKED ISSUE #1799: Support referencing directly the Gitlab project ID in a hosted gitlab deployment to allow releases on nested subgroups
Hosted Gitlab instances (all levels, CE and Enterprise) support organising repositories in a group/subgroup hierarchy.

Subgroups are accessible through the standard Interface as:
https://gitlab.mycompany.com/Group/SubgroupLvl1/SubgroupLvl2/myproject

Unfortunately, there's no direct way to access a repo residing under a nested subgroup with a single API cal, E.G, calling the API with
https://gitlab.mycompany.com/api/v4/projects/Group/SubgroupLvl1/SubgroupLvl2/myproject will give a 404 error, so the current version of ocireleaser does not support it

The current approach suggested by the Gitlab devs for accessing a project nested under subgroups is to use the API to walk the group/subgroup tree to the leaf, get the project internal ID, and use that when accessing the api/v4/projects/ REST endpoint
This would require adding some logic to the gitlab release config to indicate we're using a subgroup and it would require to implement the tree walk in order to get to the project id

A workaround that does not require modifications to the current config would be to use the project id directly as in:

```
release:
  # Name has to be configured with the project's GITLAB ID
  gitlab:
    owner: ""
    name: 62
```
This 'almost works' straight away, but the current logic for building the API url assumes the "owner" field will always have a value and adds an additional (urlencoded) slash to the path, that causes the actual API call to fail:

Goreleaser error:
```
  ⨯ release failed after 12.05s error=github/gitlab/gitea releases: failed to publish artifacts: GET https://gitlab.mycompany.com/api/v4/projects//62/releases/v1.0: 404 {message: 404 Project Not Found}
```

Gitlab API logs:
```
{"time":"2020-09-08T08:33:48.811Z","severity":"INFO","duration_s":0.05479,"db_duration_s":0.01603,"view_duration_s":0.03876,"status":404,"method":"GET","path":"/api/v4/projects/%2F62/releases/v1.0","params":[],"host":"gitlab.mycompany.com","remote_ip":"XXXXXXXX, 127.0.0.1","ua":"go-gitlab","route":"/api/:version/projects/:id/releases/:tag_name","user_id":25,"username":"gitlab-ci-gorelease","queue_duration_s":0.017381,"redis_calls":1,"redis_duration_s":0.00033,"redis_read_bytes":163,"redis_write_bytes":35,"redis_cache_calls":1,"redis_cache_duration_s":0.00033,"redis_cache_read_bytes":163,"redis_cache_write_bytes":35,"correlation_id":"cSVp6WeCAe2","meta.user":"gitlab-ci-gorelease","meta.caller_id":"/api/:version/projects/:id/releases/:tag_name"}
```

My proposal is to allow an empty owner field in the configuration file, and change the API url composing logic to ignore the field when it's empty, e.g:

in Gitlab.go, line 200, change
```
projectID := ctx.Config.Release.GitLab.Owner + "/" + ctx.Config.Release.GitLab.Name
```

to 
```
projectID := ctx.Config.Release.GitLab.Name
if (ctx.Config.Release.GitLab.Owner != ""){
  projectID = ctx.Config.Release.GitLab.Owner + "/" + projectID
}
```

If needed, I would be able to provide a pull request
```

### PR DESCRIPTION
**Pull request by mattiarossi**
**If applied, this commit will...**
Add support for using Gitlab's internal project id instead of the owner/name slug, necessary to be able to create releases on nested subgroups in Gitlab CE Hosted (See #1799)
It will also add templating support for the gitlab->name field, so that the project ID can be passed in using environment variables (e.g: name: "{{.Env.CI_PROJECT_ID}}" in a gitlab runner) 

**Why is this change being made?**
The current version of goreleaser is unable to create a gitlab release in a project that resides in a nested subgroup/group

### CODE REVIEW

**Comment by caarlos0** [comment]
I would say to make it more specific and just add a third option, `projectID`.

Fail the execution if projectID is used within github or gitea (which not support it) or if it is used together with owner/name (as per my understanding it is either owner + name or project id).

Also we need to add tests for all this...

**Comment by thynquest** [comment]
Hello there 
Any news about this feature ? I have the same problem declared at the #1799 
thank you for your help

**Comment by thynquest** [comment]
Hello there 
Any news about this feature ? I have the same problem declared at #1799 
thank you for your help

**Comment by mattiarossi** [comment]
@caarlos0: it was my understanding by looking at other issued that adding new configuration options specific to a target was not an option.
If that is something that would be approved I agree it would make for a much cleaner solution

**Comment by caarlos0** [comment]
> If that is something that would be approved I agree it would make for a much cleaner solution

yes please, will probably be better

thanks

**Comment by jessequinn** [comment]
Hi, what needs to be done here? Just waiting on approval?

**Comment by mavogel** [comment]
@mattiarossi could you rebase on master? We're happy to add this feature but there were some changes regarding the release process for gitlab: #2218 . Ping if you need support

**Comment by jessequinn** [comment]
@mavogel would this be appropriate, i do a PR that contains the same changes to help speed up the process here?

**Comment by mavogel** [comment]
closing in favor of #2297

**Pull request closed without merging**
