### PR TITLE
feat: add filter artifacts by name in uploads

### PR DESCRIPTION
**Pull request by reddec**
This commit adds filtering artifacts by name using regular expression for `uploads` section.

It could useful for uploading to servers only selected files (like only `.deb` to debian repo)

It is partially relevant to #1202, #15

### CODE REVIEW

**Comment by caarlos0** [comment]
# [Codecov](https://codecov.io/gh/goreleaser/goreleaser/pull/1357?src=pr&el=h1) Report
> Merging [#1357](https://codecov.io/gh/goreleaser/goreleaser/pull/1357?src=pr&el=desc) into [master](https://codecov.io/gh/goreleaser/goreleaser/commit/4a4e947f8dbdab1e467b9109575c1f3b28c9cae6&el=desc) will **decrease** coverage by `0.15%`.
> The diff coverage is `n/a`.

[Impacted file tree graph](https://codecov.io/gh/goreleaser/goreleaser/pull/1357?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master    #1357      +/-   ##
==========================================
- Coverage   83.88%   83.73%   -0.16%     
==========================================
  Files          57       57              
  Lines        3327     3333       +6     
==========================================
  Hits         2791     2791              
- Misses        456      461       +5     
- Partials       80       81       +1     
```



------

[Continue to review full report at Codecov](https://codecov.io/gh/goreleaser/goreleaser/pull/1357?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/goreleaser/goreleaser/pull/1357?src=pr&el=footer). Last update [4a4e947...aabdd3e](https://codecov.io/gh/goreleaser/goreleaser/pull/1357?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

**Comment by reddec** [comment]
@caarlos0 @mgrachev could you please be so kind  if you will have a moment to take look onto PR?

**Comment by caarlos0** [comment]
have you tried giving an id to, for example, the archive section and filter by that id on upload?

I don't think we actually need this 🤔

**Comment by reddec** [comment]
Unfortunately - yes, I tried.

```yaml
nfpms:
  - id: debian
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      Linux: linux
      386: i386
    homepage: https://github.com/reddec/jsonrpc2
    maintainer: Baryshnikov Aleksandr <owner@reddec.net>
    description: Tiny generator for Go to expose interfaces over JSON-RPC
    license: Mozilla Public License Version 2.0
    formats:
      - deb
uploads:
  - name: bintray
    method: PUT
    mode: archive
    username: reddec
    custom_artifact_name: true
    ids:
      - debian
    target: '{{if false}}https://api.bintray.com/content/reddec/debian/{{ .ProjectName }}/{{ .Version }}/{{ .ArtifactName }};publish=1;deb_component=main;deb_distribution=all{{end}}'
```

not worked

**Comment by reddec** [comment]
Feels like filter  by ID in the `upload` pipe relies on extra field `ID` in a context, however NFPM pipe is not filling it. In addition filtering by pattern seems to be very flexible. I also tried to fit changes to the project approach (aka use `Filter` with `And` operation). 

Am I missing something?

**Comment by caarlos0** [comment]
> eels like filter by ID in the `upload` pipe relies on extra field `ID` in a context, however NFPM pipe is not filling it. In addition filtering by pattern seems to be very flexible. I also tried to fit changes to the project approach (aka use `Filter` with `And` operation).

Correct, bug :(

**Comment by caarlos0** [comment]
fixed on master, can you try?

**Comment by reddec** [comment]
Looks like filter by id now working

**Comment by reddec** [comment]
However it's still not very usable (to upload to bintray), because I need to construct an URL with `{{.Arch}}` parameter (ex: `deb_architecture=amd64`) and this parameter is not available in archive mode that used by NFPM.
With pattern filter I can at least manually add each section for each architecture.

**Comment by reddec** [comment]
To be more specific, I can not todo like this:

```yaml

uploads:
  - name: bintray
    method: PUT
    mode: archive
    username: reddec
    custom_artifact_name: true
    ids:
      - debian
    target: 'https://api.bintray.com/content/reddec/debian/{{ .ProjectName }}/{{ .Version }}/{{ .ArtifactName }};publish=1;deb_component=main;deb_distribution=all;deb_architecture={{ .Arch }}'
```

and can't use binary mode - NFPM is using archive mode

With pattern filter I could do (at least):


```yaml

uploads:
  - name: bintray
    method: PUT
    mode: archive
    username: reddec
    custom_artifact_name: true
    pattern: ".*amd64\\.deb$"
    ids:
      - debian
    target: 'https://api.bintray.com/content/reddec/debian/{{ .ProjectName }}/{{ .Version }}/{{ .ArtifactName }};publish=1;deb_component=main;deb_distribution=all;deb_architecture=amd64'
  - name: bintray
    method: PUT
    mode: archive
    username: reddec
    pattern: ".*armv7\\.deb$"
    custom_artifact_name: true
    ids:
      - debian
    target: 'https://api.bintray.com/content/reddec/debian/{{ .ProjectName }}/{{ .Version }}/{{ .ArtifactName }};publish=1;deb_component=main;deb_distribution=all;deb_architecture=armv7'
```

**Comment by reddec** [comment]
Ping @caarlos0  @mgrachev

**Comment by caarlos0** [comment]
> However it's still not very usable (to upload to bintray), because I need to construct an URL with `{{.Arch}}` parameter (ex: `deb_architecture=amd64`) and this parameter is not available in archive mode that used by NFPM.
> With pattern filter I can at least manually add each section for each architecture.

we can make this available on the template I think

the name filter seems like a workaround for that

**Comment by caarlos0** [comment]
BTW sorry for the delay, life has been kind of crazy lately 🙏

**Comment by reddec** [comment]
Thanks, now working!

**Pull request closed without merging**
