### PR TITLE
change test so can detect if git repo is actually a parent dir

### PR DESCRIPTION
**Pull request by dpastoor**
## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x ] I have read the **CONTRIBUTING** document.
- [ ] `make ci` passes on my machine.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

tweaked the detection mechanism to shell out to git, such that can detect if the folder is contained in a git repo. This is common if using goreleaser from a monorepo, such that there may even be multiple goreleaser files in a single git repository.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 8d6f4de0e8f841ce3a8ed8025b44db77018994b0
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 8d6f4de0e8f841ce3a8ed8025b44db77018994b0
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 90da9904b6bd5cac414d2aaef4b96dbbc233c096
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 8d6f4de0e8f841ce3a8ed8025b44db77018994b0
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 90da9904b6bd5cac414d2aaef4b96dbbc233c096
  * Your commit message does not contain a body
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by dpastoor** [comment]
I am actually going to close this to squash and git a proper commit message

**Comment by caarlos0** [comment]
I ended up having a patch ready when you opened the PR, and I think mine is checking for the repo in a more safe way. Check #403

**Comment by dpastoor** [comment]
awesome - thanks for the quick fix!

**Pull request closed without merging**
