### PR TITLE
fix: brew multiple archives on one tap

### PR DESCRIPTION
**Pull request by mavogel**
## If applied, this commit will...

Hotfixes #1146 for backward compatibility

## Why is this change being made?

Atm is possible to build multiple `arm` artifacts with different `goarm` versions (v5, v6 and v7) `brew` can only handle one arm version for the formula, so if multiple versions are present brew will use the latest.

I'm still looking for a better error msg of 
```go
var ErrMultipleArchivesSameOS = errors.New("one tap can handle only 1 linux and 1 macos archive")
```

## Provide links to any relevant tickets, URLs or other resources

- #1148 
- #1140

### CODE REVIEW

**Comment by caarlos0** [comment]
I'm not sure about this 🤔 

its not like arm7 replaces arm6... its more or less like saying amd64 replaces i386... 

This is good as a hotfix, but I think we need to make it work for "all" given arm artifacts 🤔

maybe someone from the homebrew team can help with that - I don't even know if homebrew is actually supported on those envs... the site mentions something about a ["best effort basis"](https://docs.brew.sh/Homebrew-on-Linux#arm).

Maybe we should really just drop arm support from the brew pipe as well 🤔

**Comment by mavogel** [comment]
Unfortunately, I couldn't find either a brew formula supporting multiple non-64-bit arm versions. I only found [armv8 or armv6](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/hardware.rb#L147). 

> maybe someone from the homebrew team can help with that

Do they have slack or all goes via gh issues?

**Comment by caarlos0** [comment]
> Do they have slack or all goes via gh issues?

afaik github issues, but I may be dead wrong

**Comment by mavogel** [comment]
Let's see what happens: https://discourse.brew.sh/t/multiple-arm-32-bit-binaries-build-with-golang-which-to-use-in-formula/5757

**Comment by mavogel** [comment]
ping @caarlos0 : what you think regarding the answers? 

> Generally homebrew takes the upstream default for stuff so I’d say 6

shall we go with `armv6`  if it is present, if not go with the latest? 

Or wait here and extend homebrew to support multiple arm versions but I have no clue how to implement this atm

> it should technically be possible but the easiest way might be to let golang detect the processor

**Comment by caarlos0** [comment]
Another option would be to let the user choose which goarm they want, defaulting to 6 otherwise...

what do you think?

**Comment by mavogel** [comment]
Yes, sounds good to me. I'll provide a `goarm` property though in the brew section

**Comment by mavogel** [comment]
@caarlos0 I implemented it the way that `goarm` filters over all artifacts. If there are multiple builds, each with multiple 32-bit arm versions and in the brew section no ids are specified, hence we still have multiple 32-bit arm versions, then the section still fails. I improved the `ErrMultipleArchivesSameOS` therefore

**Comment by caarlos0** [comment]
awesome, thanks!

**Comment by mavogel** [comment]
shall we release a patch?

**Comment by caarlos0** [comment]
yes, will do it now :)

**Pull request merged**
