### PR TITLE
feat: make goos and goarch available in hooks

### PR DESCRIPTION
**Pull request by till**
I was looking for that, and saw the ticket. Figured, I'd try to add it and it seems to work. :)

I'm parsing the relevant values from "target", everything else seemed not feasible. And I didn't want to muck around in env unless necessary.

Resolves: #1518

### CODE REVIEW

**Comment by caarlos0** [comment]
Thanks!

**Comment by till** [comment]
@caarlos0 No, thank you for goreleaser! 🚀

**Comment by till** [comment]
@caarlos0 Any chance to get this into a release?

**Comment by caarlos0** [comment]
yes, probably today or tomorrow...

**Pull request merged**
