### PR TITLE
fix: retry upload

### LINKED ISSUE #899: retry upload on error
Right now it's possible for goreleaser to fail uploading artefacts (see https://github.com/weaveworks/eksctl/issues/364#issuecomment-449556800). This can be mitigated by retrying. It should really retry by default.

### PR DESCRIPTION
**Pull request by caarlos0**
closes #899

### CODE REVIEW

**Comment by errordeveloper** [comment]
Strangely enough, I faced this error today:

```
release failed after 363.89s error=GitHub Releases: failed to publish artifacts: stat dist/eksctl_checksums.txt: use of closed file
```

**Comment by errordeveloper** [comment]
Reverting to v0.77.2 solve the issue.

**Comment by caarlos0** [comment]
this change wasn't released yet... will do it now =)

**Comment by errordeveloper** [comment]
I have tested this using the commit hash. Please look into what may have
caused the error, if you can :) thanks!

**Comment by caarlos0** [comment]
> I have tested this using the commit hash. Please look into what may have caused the error, if you can :) thanks!

dumb mistake from me... opened #904 to fix it.

**Pull request merged**
