### PR TITLE
adding draft support

### PR DESCRIPTION
**Pull request by caarlos0**
ref #183 

Question remaining: what should happen in the brew pipe when the release is a draft? Should we skip it?

### CODE REVIEW

**Comment by bep** [comment]
That is a good question. How would you "finish" that brew publish when it's paused?

I would say that, for now, just make it crystal clear that this is for GitHub and GH only. And then think about a more thought through solution for the others (there will be others); maybe some kind of holding persistent "holding queue" ...

**Comment by caarlos0** [comment]
@bep let me know what you think:

"Normal" release process:

- create release
- upload artifacts
- open branch on tap repo
- edit the formula in that branch
- open PR
- merge the PR 
- delete the branch

"Draft" release process:

- create draft release
- upload artifacts
- open branch on tap repo
- edit the formula in that branch
- open PR

So, to approve, the user need to publish the release and merge the PR.

What do you think?

**Comment by bep** [comment]
I'm not totally sure that I follow you.

Currently you

1) Manually create a tag on any branch you want
2) Run goreleaser which creates and publishes a release on GitHub

There is not automatic pull request merging in the above, to my knowledge, which is fine.

So, in the refined logic, I would assume was limited to the "not auto publish the GitHub release?" but there may be logic re. Homebrew etc. that I have not touched yet.

**Comment by caarlos0** [comment]
@bep Yeah, maybe I just went full crazy in this one (I'm on painkillers, sorry about that).

The idea was that, if the release is a draft, instead of creating/updating the tap, it would open a PR and let it open, so in order to really publish the release, the user would have to Publish the release AND merge that PR.

But maybe this is too much... I'm actually not sure at all how this should be handled.

**Comment by bep** [comment]
I will sleep on this, but I suspect you in parts reinvent the wheel that GitHub does pretty great -- and  if you don't produce any artifacts (other than the binaries and the changelog that does not (as I currently see it) have any place in the released source; I'm not sure what you're "pulling in" as a pull request. 

I have built a kind of harness/workflow in Hugo to handle version updates, release notes etc., and, while I may contribute some of this back to Goreleaser when I figure out what may be general enough, I think many projects have to specific needs to tailor in a good way in this department.

What I would like in a draft feature would be:

1) First of all the obvious: Be able to mark the release as a draft in GitHub
2) On a more advanced level, a way to "hold" the other publication channels (Brew, ...) until I somehow approve it (aka `release --continue``).

**Comment by caarlos0** [comment]
@bep yeah, I guess your idea is better.

So, I'll just leave this PR here and start a new one, which will just mark the release as draft and skip the brew pipe entirely. 

Next: serialize the current context to a `ctx.json` file or something, and be able to load it back and continue with `--continue` flag.

**Comment by bep** [comment]
Probably overkill for this, but BoltDB is great for lightweight embedded db stuff.

**Pull request closed without merging**
