### PR TITLE
add: Scoop.sh app manifest generation

### PR DESCRIPTION
**Pull request by Southclaws**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] I have read the **CONTRIBUTING** document.
- [ ] `make ci` passes on my machine.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

This PR includes the changes I made for #387 - it's quite late but I've recently hit the need for it again so I decided to put some time into it. I've tested on my sampctl project and it's generating manifests okay.

> `make ci` passes on my machine.
This didn't 100% work because it attempts to push to a Docker registry 

> I have updated the documentation accordingly.
I will update the docs once maintainers are happy with the code changes and config interface.

> I have added tests to cover my changes.
There are some, I will be adding more when I get time.

### CODE REVIEW

**Comment by caarlos0** [comment]
> This didn't 100% work because it attempts to push to a Docker registry

you should only need to have docker running, it fires up and pushes to a local docker registry...

**Comment by caarlos0** [comment]
if I understood correctly, it will generate a single scoop for all windows64 binaries, right? Is this ok (on the scoop side of things)?

**Comment by Southclaws** [comment]
> you should only need to have docker running, it fires up and pushes to a local docker registry...
Oh okay, I'll give it another try tomorrow, it was throwing a lot of errors about registry permissions so I'll check the output a bit closer.

> if I understood correctly, it will generate a single scoop for all windows64 binaries
Yeah for now, I did have it add each binary to the `urls` section but I'm currently travelling only with a macbook so I'm keeping it simple until I can test with a project that actually has multiple binaries.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4a94cc181f2859671d2b228294673e68ea018945
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4a94cc181f2859671d2b228294673e68ea018945
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4a94cc181f2859671d2b228294673e68ea018945
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4a94cc181f2859671d2b228294673e68ea018945
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4a94cc181f2859671d2b228294673e68ea018945
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 9a21bad35325bbfd4a4c7c4196cd9010d6b04210
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4a94cc181f2859671d2b228294673e68ea018945
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: 9a21bad35325bbfd4a4c7c4196cd9010d6b04210
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by caarlos0** [comment]
hey @Southclaws, can you merge with master? There are a lot of conflicts here :(

**Comment by Southclaws** [comment]
Unfortunately I didn't have time to resolve all the conflicts, too much has changed.

**Comment by caarlos0** [comment]
@Southclaws :/

**Comment by Southclaws** [comment]
I might try rewriting it on a fresh fork this weekend if I get time.

**Comment by caarlos0** [comment]
nice, let me know if you need any help

**Pull request closed without merging**
