### PR TITLE
fix: honouring ko bare option

### PR DESCRIPTION
**Pull request by kameshsampath**
The commit will add the `bare` option to ko publisher options when set/passed via config `.goreleaser.yaml`.

Currently, even the `bare: true` is set via config,  the option was never passed to `ko` PublisherOptions.

#3742

### CODE REVIEW

**Comment by developer-guy** [comment]
PTAL @imjasonh, I wrote this code, but TBH, I didn't get the idea of using the `fromEnv` option. Is it safe to remove this control, can you please help us with that?

**Comment by developer-guy** [comment]
@kameshsampath let's wait until Jason who is the author of the ko project comments, if he says this is okay to be removed then we can merge this PR. Does that make sense?

**Comment by kameshsampath** [comment]
@developer-guy 

> PTAL @imjasonh, I wrote this code, but TBH, I didn't get the idea of using the fromEnv option. Is it safe to remove this control, can you please help us with that?

My rationale removing it is that I did not find any difference between two blocks, and why the `repo` variable was used as we can set the PublisherOpts via `buildOpts` 

As you suggested lets wait for @imjasonh  comments

**Review by caarlos0 — COMMENTED** [review]
lgtm, I think we can then also remove the `opts.fromEnv` et al?

**Comment by caarlos0** [comment]
confirming: yes we can:

```diff
diff --git a/internal/pipe/ko/ko.go b/internal/pipe/ko/ko.go
index 9488348b..30b05641 100644
--- a/internal/pipe/ko/ko.go
+++ b/internal/pipe/ko/ko.go
@@ -109,7 +109,6 @@ func (Pipe) Default(ctx *context.Context) error {

                if repo := ctx.Env["KO_DOCKER_REPO"]; repo != "" {
                        ko.Repository = repo
-                       ko.RepositoryFromEnv = true
                }

                if ko.Repository == "" {
@@ -136,7 +135,6 @@ type buildOptions struct {
        flags               []string
        env                 []string
        imageRepo           string
-       fromEnv             bool
        workingDir          string
        platforms           []string
        baseImage           string
@@ -225,28 +223,17 @@ func doBuild(ctx *context.Context, ko config.Ko) func() error {
                        return fmt.Errorf("build: %w", err)
                }

-               po := []publish.Option{publish.WithTags(opts.tags), publish.WithAuthFromKeychain(keychain)}
-
-               var repo string
-               if opts.fromEnv {
-                       repo = opts.imageRepo
-               } else {
-                       // image resource's `repo` takes precedence if set, and selects the
-                       // `--bare` namer so the image is named exactly `repo`.
-                       repo = opts.imageRepo
-                       po = append(po, publish.WithNamer(options.MakeNamer(&options.PublishOptions{
-                               DockerRepo:          opts.imageRepo,
-                               Bare:                opts.bare,
-                               PreserveImportPaths: opts.preserveImportPaths,
-                               BaseImportPaths:     opts.baseImportPaths,
-                       })))
-               }
+               po := []publish.Option{publish.WithTags(opts.tags), publish.WithNamer(options.MakeNamer(&options.PublishOptions{
+                       DockerRepo:          opts.imageRepo,
+                       Bare:                opts.bare,
+                       PreserveImportPaths: opts.preserveImportPaths,
+                       BaseImportPaths:     opts.baseImportPaths,
+                       Tags:                opts.tags,
+               })), publish.WithAuthFromKeychain(keychain)}

-               p, err := publish.NewDefault(repo, po...)
-               if err != nil {
-                       return fmt.Errorf("newDefault: %w", err)
-               }
+               p, err := publish.NewDefault(opts.imageRepo, po...)
                defer func() { _ = p.Close() }()
+
                if _, err = p.Publish(ctx, r, opts.importPath); err != nil {
                        return fmt.Errorf("publish: %w", err)
                }
@@ -302,7 +289,6 @@ func buildBuildOptions(ctx *context.Context, cfg config.Ko) (*buildOptions, erro
                platforms:           cfg.Platforms,
                sbom:                cfg.SBOM,
                imageRepo:           cfg.Repository,
-               fromEnv:             cfg.RepositoryFromEnv,
        }

        tags, err := applyTemplate(ctx, cfg.Tags)
diff --git a/internal/pipe/ko/ko_test.go b/internal/pipe/ko/ko_test.go
index 3bef16f5..c3982592 100644
--- a/internal/pipe/ko/ko_test.go
+++ b/internal/pipe/ko/ko_test.go
@@ -44,18 +44,17 @@ func TestDefault(t *testing.T) {
        })
        require.NoError(t, Pipe{}.Default(ctx))
        require.Equal(t, config.Ko{
-               ID:                "test",
-               Build:             "test",
-               BaseImage:         chainguardStatic,
-               Repository:        registry,
-               RepositoryFromEnv: true,
-               Platforms:         []string{"linux/amd64"},
-               SBOM:              "spdx",
-               Tags:              []string{"latest"},
-               WorkingDir:        ".",
-               Ldflags:           []string{"{{.Env.LDFLAGS}}"},
-               Flags:             []string{"{{.Env.FLAGS}}"},
-               Env:               []string{"SOME_ENV={{.Env.LE_ENV}}"},
+               ID:         "test",
+               Build:      "test",
+               BaseImage:  chainguardStatic,
+               Repository: registry,
+               Platforms:  []string{"linux/amd64"},
+               SBOM:       "spdx",
+               Tags:       []string{"latest"},
+               WorkingDir: ".",
+               Ldflags:    []string{"{{.Env.LDFLAGS}}"},
+               Flags:      []string{"{{.Env.FLAGS}}"},
+               Env:        []string{"SOME_ENV={{.Env.LE_ENV}}"},
        }, ctx.Config.Kos[0])
 }

diff --git a/pkg/config/config.go b/pkg/config/config.go
index 13b2ff04..aabbeb6f 100644
--- a/pkg/config/config.go
+++ b/pkg/config/config.go
@@ -207,7 +207,6 @@ type Ko struct {
        WorkingDir          string   `yaml:"working_dir,omitempty" json:"working_dir,omitempty"`
        BaseImage           string   `yaml:"base_image,omitempty" json:"base_image,omitempty"`
        Repository          string   `yaml:"repository,omitempty" json:"repository,omitempty"`
-       RepositoryFromEnv   bool     `yaml:"-" json:"-"`
        Platforms           []string `yaml:"platforms,omitempty" json:"platforms,omitempty"`
        Tags                []string `yaml:"tags,omitempty" json:"tags,omitempty"`
        SBOM                string   `yaml:"sbom,omitempty" json:"sbom,omitempty"`
```

**Comment by kameshsampath** [comment]
thanks for the review @caarlos0, I have made those changes and pushed it back.

@developer-guy / @imjasonh  - let me know if thats OK with you both

**Review by imjasonh — APPROVED** [review]

**Review by developer-guy — APPROVED** [review]

**Comment by caarlos0** [comment]
Thanks everyone!

**Pull request merged**
