### PR TITLE
feat: Checksums as a template field

### PR DESCRIPTION
**Pull request by caarlos0**
this would allow to add the checksums to the body of the release contents, for example.

refs https://github.com/orgs/goreleaser/discussions/4063

### CODE REVIEW

**Comment by sethiyash** [comment]
Will this be available as part of Goreleaser PRO?

**Comment by sethiyash** [comment]
@caarlos0 when this will be available as part of goreleaser/goreleaser-action

When I'm trying with version 1.19.0 in goreleaser-action it is throwing the below error - 

```
```
{{ .Checksums }}
```
 } [] [] [] [] [] [] [] { [] {    {  } {false {  } false}} {    {  } {false {  } false}}  { }      []  [] [] [] [] } [] [{ [linux windows darwin] [amd64 arm64] [] [] [] [] [{windows arm64   }]  ./cmd/kapp kapp-{{ .Os }}-{{ .Arch }} {[] []}   false   false false   { [-buildid= -X github.com/vmware-tanzu/carvel-kapp/pkg/kapp/version.Version={{ .Version }}] [] [-trimpath] [] [] [CGO_ENABLED=0]} []}] [{ [] {  ----------  0001-01-01 00:00:00 +0000 UTC} {{ .Binary }} binary []  false  [] false false}] [] [] {{{ .Tag }}-next} {checksums.txt sha[25](https://github.com/sethiyash/carvel-kapp/actions/runs/5463677938/jobs/9944668053#step:5:26)6 [] false []} [] [] [] [] [] [] {{[] [^docs: typo]} asc false  [] 0}  [] [] {  } {[]} {  false  [] } {false []  } { {false } {false  } {false     } {false      [] []} {false    } {false    } {false  0   []   false} {false       } {false } {false   } {false false   map[] } {false   }} [] [] { } false [] [] { [] [] [] [] [] [] []    {[] []}   false   false false   { [] [] [] [] [] []} []}  {   false} {  false false false} {  false}}
  ⨯ release failed after 0s                  error=yaml: unmarshal errors:
  line 29: field replacements not found in type config.Archive
Error: The process '/opt/hostedtoolcache/goreleaser-action/1.19.0/x64/goreleaser' failed with exit code 1
```

**Comment by sethiyash** [comment]
This is how my release section of .goreleaser.yml look like - 
```
release:
  # Repo in which the release will be created.
  github:
    owner: carvel-dev
    name: kapp

  draft: true

  prerelease: auto

  footer: |
    # :open_file_folder: Files Checksum
    ```
    {{ .Checksums }}
    ```

  # use to change the name of the release.
  name_template: "{{.Tag}}"
```

**Comment by caarlos0** [comment]
It is already available in 1.19

The error you get is because of this: https://goreleaser.com/deprecations/?h=depre#archivesreplacements

**Pull request merged**
