### PR TITLE
fix: cleanup/tidy go.mod deps

### PR DESCRIPTION
**Pull request by tpounds**
Cleanup/tidy `go.mod` dependencies. Should fix similar issues in downstream projects using `go get` or pinning a specific versions with `go.mod` and a `tools.go` file.

see:
#1145
https://github.com/goreleaser/godownloader/issues/133
https://github.com/golangci/golangci-lint/issues/730

### CODE REVIEW

**Comment by caarlos0** [comment]
build is failing due to unrelated changes.

**Comment by caarlos0** [comment]
thanks btw!

**Comment by tpounds** [comment]
@caarlos0 Thanks for merging! Would it be possible to get a release version containing this fix?

**Comment by caarlos0** [comment]
@tpounds thanks for the pr, just cut v0.118.1 🚀

**Pull request merged**
