### PR TITLE
feat: multi-arch docker images

### PR DESCRIPTION
**Pull request by caarlos0**
- [x] first impl
- [x] tests
- [x] docs
- [ ] refine impl/api probably after reviews 👼 
- [ ] manifest push sometimes fails on my machine, seems to be related to https://github.com/docker/distribution/issues/3100
- [x] goreleaser multi-arch images?

closes https://github.com/goreleaser/goreleaser/issues/530

### CODE REVIEW

**Comment by caarlos0** [comment]
I heard @gianarb will be happy to see this...

**Comment by ryancurrah** [comment]
I do not see any annotations being created in the manifest pipe after creating the manifest: 

`docker manifest annotate 45.55.81.106:5000/coolapp:v1 45.55.81.106:5000/coolapp-arm-linux --arch arm`.

**Comment by caarlos0** [comment]
it creates with `docker manifest create` and already amends all given images in a single command...

**Comment by ryancurrah** [comment]
Ah cool! I read the Docker docs this morning after getting notified about the recent `goreleaser` release and digging into this new feature. It was not clear if the annotations had to be manually set. I did look around for clearer docs but not to much info about manifests atm.

**Comment by oldthreefeng** [comment]
youre doing great job~

**Pull request merged**
