### PR TITLE
feat: Add support for specifying SSE on S3 objects

### LINKED ISSUE #1045: Add support for setting server-side encryption on S3 objects
**Is your feature request related to a problem? Please describe.**
We recently turned on KMS-based server-side encryption requirements for all buckets in our organization, and started running into issues with goreleaser getting "Access Denied" errors when trying to upload a release into our private bucket.

**Describe the solution you'd like**
I'd like to see support for specifying `aws:kms` or `AES256` encryption on uploaded objects. (akin to `aws s3 cp --sse aws:kms local_object s3://bucket/remote_key`)

**Describe alternatives you've considered**
The other option is to not let GoReleaser upload to S3, and instead use `aws s3 ...` ourselves (in CI).

### PR DESCRIPTION
**Pull request by rafaelmagu**
If applied, this commit will add support for specifying Server-Side Encryption (SSE) on uploaded S3 objects, both with default encryption and with custom-specified keys.

**Note**: I added this to the now-deprecated `s3` handler. I could not find a good example of how to set SSE for the `blob` handler.

There is currently no support for SSE on uploaded S3 objects.

Closes #1045

### CODE REVIEW

**Comment by C123R** [comment]
> **Note**: I added this to the now-deprecated `s3` handler. I could not find a good example of how to set SSE for the `blob` handler.

Currently, I guess it's not possible to integrate SSE for the blob provider we have, as we are using GO CDK and which is not supporting SSE(not sure if they are), have to check this.
But logically we can integrate this in future as like S3, Azure and GCS also support SSE using default + their respective Key Managed Systems.

**Comment by rafaelmagu** [comment]
@caarlos0 forgive me for my noobness, but I don't know where to start with Golang testing (I'm pretty new to Golang myself). Do you have any pointers on where to look first to understand it more?

@C123R it looks like the Go CDK supports provider-specific properties: https://stackoverflow.com/questions/55308878/attempting-to-convert-some-code-to-go-cdk-when-using-kms/55360616#55360616

I don't know enough about the Go CDK to interpret that code to a point where I can add the enhancement in this PR to the `blob` handler.

**Comment by caarlos0** [comment]
hey @rafaelmagu can you try https://github.com/goreleaser/goreleaser/pull/1056?

your key should be something like:
- `awskms://1234abcd-12ab-34cd-56ef-1234567890ab?region=us-east-1`
- `gcpkms://projects/MYPROJECT/locations/MYLOCATION/keyRings/MYKEYRING/cryptoKeys/MYKEY`
- `azurekeyvault://mykeyvaultname.vault.azure.net/keys/mykeyname`

let me know if it works

**Comment by caarlos0** [comment]
@rafaelmagu can you check if #1056 works now?

**Comment by rafaelmagu** [comment]
Closing this as there's better support coming in #1056

**Pull request closed without merging**
