### PR TITLE
migrating to vgo

### LINKED ISSUE #764: prepare for vgo
we should test if everything works fine under vgo, and possibly migrate to it, so users could `go get` under go 1.11 :)

### PR DESCRIPTION
**Pull request by caarlos0**
closes #764

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4e54bb7de73c4f2168e53624e05568e578ef6048
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, add, remove, move, bump, update, release**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4e54bb7de73c4f2168e53624e05568e578ef6048
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, add, remove, move, bump, update, release**

 * Commit: f6e7d5af84ed5c05546152eb5a57acd30111e86f
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, add, remove, move, bump, update, release**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4e54bb7de73c4f2168e53624e05568e578ef6048
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, add, remove, move, bump, update, release**

 * Commit: f6e7d5af84ed5c05546152eb5a57acd30111e86f
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, add, remove, move, bump, update, release**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4e54bb7de73c4f2168e53624e05568e578ef6048
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, add, remove, move, bump, update, release**

 * Commit: f6e7d5af84ed5c05546152eb5a57acd30111e86f
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, add, remove, move, bump, update, release**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 4e54bb7de73c4f2168e53624e05568e578ef6048
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, add, remove, move, bump, update, release**

 * Commit: f6e7d5af84ed5c05546152eb5a57acd30111e86f
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, add, remove, move, bump, update, release**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by caarlos0** [comment]
Need to wait for https://github.com/golangci/golangci-lint/issues/178

**Pull request closed without merging**
