### PR TITLE
feat: Add support for publishing to additional docker registries

### PR DESCRIPTION
**Pull request by caalberts**
Created a list of registries based on the docker image name and
additional registries. Image is then tagged with all permutations
of registry and tags.

See #832

### CODE REVIEW

**Comment by flyinprogrammer** [comment]
LGTM

**Comment by caarlos0** [comment]
Hi, many thanks for the PR! 🎉

maybe it would be more flexible if we had a `image_templates`? I'm thinking that maybe the user wants to push some tags to a given registry and other just to another set of registries or something like that, so the config would look like:

```yaml
# .goreleaser.yml
dockers:
  # You can have multiple Docker images.
  -
    # GOOS of the built binary that should be used.
    goos: linux
    # GOARCH of the built binary that should be used.
    goarch: amd64
    # GOARM of the built binary that should be used.
    goarm: ''
    # Name of the built binary that should be used.
    binary: mybinary
    # Skips the docker push. Could be useful if you also do draft releases.
    # Defaults to false.
    skip_push: false
    # Path to the Dockerfile (from the project root).
    dockerfile: Dockerfile
    image_templates:
    - "foo.bar/myimage/latest"
    - "myuser/myimage/latest"
    - "myuser/myimage/{{ .Tag }}"
    - "myuser/myimage/{{ .Tag }}-{{ .Env.GO_VERSION }}"
    - "myuser/myimage/v{{ .Major }}"
    # Template of the docker build flags.
    build_flag_templates:
    - "--label=org.label-schema.schema-version=1.0"
    - "--label=org.label-schema.version={{.Version}}"
    - "--label=org.label-schema.name={{.ProjectName}}"
    - "--build-arg=FOO={{.ENV.Bar}}"
    # If your Dockerfile copies files other than the binary itself,
    # you should list them here as well.
    extra_files:
    - config.yml
```

the config would become a little bit more verbose, but it would be more flexible...

what do you think?

Cheers!

**Comment by caalberts** [comment]
This is definitely more flexible, but existing config file with `image` would break, wouldn’t it?

**Comment by caarlos0** [comment]
> This is definitely more flexible, but existing config file with `image` would break, wouldn’t it?

yes, we have a system to deprecate things (basically warns on the output and points to the documentation), so we could deprecate that and remove after a few months.

Example -> https://github.com/goreleaser/goreleaser/pull/759

**Comment by caalberts** [comment]
@caarlos0 do you intend to deprecate both `image` and `tag_templates` and replace them with just `image_templates`?

**Comment by caarlos0** [comment]
> @caarlos0 do you intend to deprecate both `image` and `tag_templates` and replace them with just `image_templates`?

yes, I think that make sense... config may become more repetitive, but it would be more flexible, so I think it is a good tradeof...

**Comment by caalberts** [comment]
I updated the PR with the changes for `image_templates`.

In summary, `image_templates` is the main configuration for docker now. For backward compatibility,`image` + `tag_templates` are still supported. However, `image_templates` and `image` + `tag_templates` cannot be used at the same time.

I assumed that at least 1 `image_template` is given, so there is no default value for that.

**Comment by caarlos0** [comment]
awesome! Thanks for the PR!

**Pull request merged**
