### PR TITLE
Changed confix syntax to accept multiple repository providers

### PR DESCRIPTION
**Pull request by caarlos0**
refs #110 

This will break compatibility with previous versions config.

### CODE REVIEW

**Comment by caarlos0** [comment]
@jorinvo yeah, I had the same feeling while doing this... maybe we should just fallback to add a `provider` property instead of changing all this

**Comment by jorinvo** [comment]
@caarlos0 good idea! I wasn't that happy with the name "repo" anyways since some possible future release targets / providers could also be of different shape than a repository.

**Comment by codeskyblue** [comment]
if goreleaser.yml has a version, break changes can be easily commit

**Comment by jorinvo** [comment]
The most flexible solution I can think of would be to have one configuration option `release` which is a list of different providers:
``` yaml
release:
  - github:
      repo: user/repo
      host: my.server.com
  - gitlab:
      repo: user/repo
      host: my.server.com
  - brew:
      repo: user/homebrew-tap
      folder: Formula
      dependencies:
        - git
        - zsh
```

This format would allow as many different release as anyone desires.
Each item would also be easy parsable by keeping settings for each type of provider in it's own property.
And yes, I would also treat brew as a release target. 

I don't think this would complicate things and it wouldn't stop use from keeping the default behavior of having no configuration at all.

**Comment by caarlos0** [comment]
@jorinvo yeah, we shall break compatibility to do that though...

Maybe we should add the new syntax and start to warn about the new syntax and let it be for a while...

**Comment by jorinvo** [comment]
@caarlos0 we can keep supporting the old syntax by keeping it as fallback.
First we try to parse the new format. If it didn't work we parse the old format.

**Comment by titpetric** [comment]
Just throwing it out there: what if you'd like to publish to two different github repositories? Would it be enough just to add:

```
- github1:
    repo: repo/name
    host: github.com
- github2:
    repo: repo/name2
   host: github.com
```

What exactly are the asumptions behind this? Does it need a HTTP/S API to push releases or is it managed with a git somehow (branch, remote?)? I actually wouldn't be that terribly upset if I deployed releases to a special git branch and pushed them to whatever origins I have (...). Maybe that's a different PR altogether :)

**Comment by jorinvo** [comment]
@titpetric 

- My idea was to make it a simple list as seen above. That way you can add as many release targets of the same type as you like.

Having two GitHub repos to release to would look like:
 
``` yaml
release:
  - github:
      repo: user/repo
  - github:
      repo: user2/repoX
      # This one being a GitHub enterprise instance
      host: my.server.com
```

As you can see `github` is just a property set for one item in the `release` list. 
For each item we would need to restrict it to setting only one provider property though.

- The `github` release target is only intended to create regular GitHub releases. It should work with github.com and also GitHub enterprise systems.
For other release mechanisms that use Git in some other way we would need to create a new provider.

**Comment by caarlos0** [comment]
@jorinvo I agree with your solution. I'll start a new branch for it.

About breaking compatibility, I guess this is the time to do it. We are not 1.0 stable yet, so, better now than later.

**Comment by caarlos0** [comment]
I re-implemented this in #145

**Comment by caarlos0** [comment]
@jorinvo I end up with an even simple syntax, check #145 when you can :)

**Pull request closed without merging**
