### PR TITLE
update retry package version

### PR DESCRIPTION
**Pull request by kamilsk**
I improved my [package](https://github.com/kamilsk/retry) and updated its major version here.

### CODE REVIEW

**Comment by kamilsk** [comment]
Also, I suggest to wrap [this](https://github.com/goreleaser/goreleaser/blob/master/internal/pipe/release/release.go#L120) by [safe.Close](https://github.com/kamilsk/platform/blob/master/pkg/safe/close.go#L5-L26) instead of use `nolint: errcheck`. It could be look like:

```go
defer safe.Close(file)
// or
defer safe.Close(file, func (err error) { log.Println(err) }) // etc
```

**Comment by caarlos0** [comment]
thanks!

**Comment by kamilsk** [comment]
@caarlos0, what do you about this https://github.com/goreleaser/goreleaser/pull/972#issuecomment-468935544 proposal? Can I add a dependency on my another package to use https://github.com/kamilsk/platform/blob/master/pkg/safe/close.go? Or it is not interesting to you. Or I can copy-paste it to your project.

**Comment by caarlos0** [comment]
no need for now, thanks for the proposal though! :)

**Comment by kamilsk** [comment]
ok, thank you for your great project. goreleaser saved me a lot of time!

**Pull request merged**
