### PR TITLE
feat: scoop shortcuts

### PR DESCRIPTION
**Pull request by howieyuen**
close: https://github.com/goreleaser/goreleaser/issues/3845

### CODE REVIEW

**Comment by howieyuen** [comment]
@caarlos0

**Comment by howieyuen** [comment]
shall I change the doc to "since 1.17" cause I wrote "1.16.1" ? @caarlos0

**Comment by caarlos0** [comment]
> shall I change the doc to "since 1.17" cause I wrote "1.16.1" ? @caarlos0

yes, new features go out on minor releases, as per semver

**Comment by howieyuen** [comment]
> > shall I change the doc to "since 1.17" cause I wrote "1.16.1" ? @caarlos0
> 
> yes, new features go out on minor releases, as per semver

ok, I'll make a force push

**Pull request merged**
