### PR TITLE
fix: duplicate draft release in GitHub

### LINKED ISSUE #3148: Do not create duplicate draft release in GitHub
### Is your feature request related to a problem? Please describe.

Our release workflow is like this:
1. Create a `vx.y.z` branch, then GitHub Actions create a draft release with the name `RELEASE vx.y.z`
2. In the next couple of day, we cherry-pick some bug-fix commit to the release branch as well as fill the content of the release note

The question is a new commit to the release branch will trigger goreleaser again, and create another draft release note (instead of appending to the existing one).

Seems like goreleaser only treat releases with the same tag as the same releases. While the draft release will be assigned a random tag like `untagged-1070a2429328d38d3638`.
 https://github.com/goreleaser/goreleaser/blob/f8e5bdac10a61271aee0ca58427fdb0432b3d10b/internal/client/github.go#L224-L230

### Describe the solution you'd like

Consider treating draft releases with the same name as the same release

### Describe alternatives you've considered

N/A

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by qsliu2017**
For draft releases in GitHub, treat other draft releases with the same name as the same release.

Fix #3148

### CODE REVIEW

**Comment by caarlos0** [comment]
this is not going to work, unless we also remove all existing release artifacts first

**Comment by qsliu2017** [comment]
updated. @caarlos0 please take a look

**Comment by caarlos0** [comment]
I wonder if it isn't easier to just delete the draft release if it already exits before creating a new one? 

thoughts?

**Comment by caarlos0** [comment]
fixed in https://github.com/goreleaser/goreleaser/pull/3318

**Pull request closed without merging**
