### PR TITLE
feat(yaml): upgraded from yaml.v2 to yaml.v3

### LINKED ISSUE #3005: upgrade yaml dependency to v3
### Is your feature request related to a problem? Please describe.

No particular problem. Just upgrade to newer dependencies.

### Describe the solution you'd like

Currently, the codebase depends on gopkg.in/yaml.v2.
There is a major release available gopkg.in/yaml.v3.

There are some breaking changes in the API, so I am suggesting wrapping yaml usage in some internal package, at least while we are transitioning. See my draft proposal https://github.com/goreleaser/goreleaser/pull/3004

There might be some other more subtle changes. Perhaps more thorough testing is needed.

For context, the issue was raised when trying to unmarshal a YAML config in some "untyped" structure to instruct lower-level pipelines and then trying to json.Marshal this back to feed external APIs: 
* YAML v2 unmarshals objects as map[interface{}]interface{}, hence requires some rework to be json.Marshal-ed
* YAML v3 uses map[string]interface{}, hence no rework

This point has been raised by PR https://github.com/goreleaser/goreleaser/pull/2988 , which introduced some boiler-plate to convert untyped structures. Specifically, raised by https://github.com/goreleaser/goreleaser/pull/2988#issuecomment-1077296226

I am balanced about the value added by such an upgrade:
* on the one hand, we benefit from the upgrade, better YAML behavior, less clutter from #2988 
* on the other hand, the go community hasn't widely moved in favor of v3, so we end up with still some indirect dependencies on v2
* other changes introduced are subtle and might break the user experience. Requires more thorough testing

Cheers,

Frederic

### Describe alternatives you've considered

The approach adopted by https://github.com/goreleaser/goreleaser/pull/2988  is to minimize impact, at the cost of some extra boiler-plate that is at the moment used only by this new feature.

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by fredbi**
* fixes #3005 

Signed-off-by: Frederic BIDON <fredbi@yahoo.com>

...

...

...

### CODE REVIEW

**Comment by caarlos0** [comment]
hmmm, only test failing seems to be indent-related

will take a look, but this looks great, thanks!

**Comment by fredbi** [comment]
@caarlos0  this was just an early draft, following a previous comment of yours. Didn't spend much time on it.
If you think that adopting yaml.v3 is a good idea, and that the internal wrapper approach is correct, I can work more on the testing.

**Comment by fredbi** [comment]
@caarlos0  : ok thanks. I will work on wrapping this up over the weekend. This shall unblock #2988, which will need less clutter.

**Comment by caarlos0** [comment]
amazing, thanks!

**Comment by fredbi** [comment]
@caarlos0  I believe it is reviewable now. I am not able to run the Vercel step, hence not able to figure out if CI is okay or not.

**Review by caarlos0 — APPROVED** [review]

**Comment by caarlos0** [comment]
This looks great, thanks @fredbi !

**Comment by fredbi** [comment]
Thanks. Now rebasing my other PR, that was awaiting for this chore to pass.

**Pull request merged**
