### PR TITLE
feat: support tar.zst archives

### PR DESCRIPTION
**Pull request by horjulf**
This adds support for `tar.zst` archives.

### CODE REVIEW

**Comment by horjulf** [comment]
@caarlos0 what do you think, anything that I might have missed ?

**Comment by caarlos0** [comment]
curious: is it common to use this compression for this usecase? I don't recall seeing it before for this 🤔

**Comment by horjulf** [comment]
Its getting well supported, its way faster than gzip while having better compression ratios.
For example tar officially supports it now, Archlinux also added support recently for distro packages.

Mostly at the moment is a very good option for internal packages or cases where you want to pull and manipulate archives programmatically due to the speed/size advantages.

**Comment by caarlos0** [comment]
not stale

**Comment by horjulf** [comment]
@caarlos0 any plans on merging this or can we drop it ?

**Comment by caarlos0** [comment]
for now I'm waiting if more people want/need this... if there isn't many I probably won't merge it in (at least not now), because it would be another format to test and maintain and etc... and once it is in we can't get it out without breaking people...

**Pull request closed without merging**
