### PR TITLE
docs: goreleaser-xx

### PR DESCRIPTION
**Pull request by crazy-max**
Cookbook that shows how to use GoReleaser with [`goreleaser-xx`](https://github.com/crazy-max/goreleaser-xx#readme) to ease the integration and cross compilation in a Dockerfile.

### CODE REVIEW

**Comment by caarlos0** [comment]
I think it is important to explain how it makes it easier to cross compile... and make it explicit wether it can be used to cross compile cgo projects or not

**Comment by crazy-max** [comment]
Yes indeed I will make a simple excerpt to explain the design.

**Comment by caarlos0** [comment]
thinking a bit more about this... it might be hard to keep this up to date... what are your thoughts about

- just stating what goreleaser-xx is and which problems it solve
- link to the repository readme or some other goreleaser-xx docs

?

**Comment by crazy-max** [comment]
> thinking a bit more about this... it might be hard to keep this up to date... what are your thoughts about
> 
>     * just stating what goreleaser-xx is and which problems it solve
> 
>     * link to the repository readme or some other goreleaser-xx docs
> 
> 
> ?

SGTM will do that, thanks mate.

**Comment by crazy-max** [comment]
Made suggested changes. Let me know if it LGTY.

**Comment by caarlos0** [comment]
amazing, thanks @crazy-max !

**Pull request merged**
