### PR TITLE
feat: make generated brew formulas `brew audit` compatible (#1908)

### PR DESCRIPTION
**Pull request by lukasmalkmus**
This PR resolves the issues described in #1908. I want to split this into two commits:

1. Add the license field (optional). If no SPDX license identifier is set, the field won't be present in the generated Formula.
2. Get rid of the whitespaces in otherwise empty lines.

Figuring the first one out was easy but I kinda struggle with the whitespaces. Really never thought that was the hard part... but gotemplates 🤦

### CODE REVIEW

**Review by caarlos0 — COMMENTED** [review]
LGTM so far :)

**Comment by caarlos0** [comment]
> Figuring the first one out was easy but I kinda struggle with the whitespaces. Really never thought that was the hard part... but gotemplates 🤦

yeah that's always the worst, maybe we can remove them after compiling the template though 🤔

**Comment by lukasmalkmus** [comment]
> yeah that's always the worst, maybe we can remove them after compiling the template though

Yes, I added that. Might be the quickest way to resolve this instead of dealing with templating (even if that would be the proper way I guess).

**Comment by lukasmalkmus** [comment]
Ready for review.

**Review by caarlos0 — APPROVED** [review]

**Comment by caarlos0** [comment]
Thanks!

**Pull request merged**
