### PR TITLE
Added custom Header and Footer to releases

### PR DESCRIPTION
**Pull request by wesleimp**
This PR makes prossible to add custom Header and Footer to your releases

### CODE REVIEW

**Comment by caarlos0** [comment]
Hey, this is already allowed, check

```console
$ goreleaser release --help
```

**Comment by wesleimp** [comment]
> Hey, thanks for the PR!
> 
> This is already allowed though, check:
> 
> ```
> $ goreleaser release --help
> ```

Sure, but I cant set the header or footer by `yml` file and I need to create `header.md` or `footer.md` to use that feature, right?

**Comment by wesleimp** [comment]
@caarlos0 should I close this PR?

**Comment by caarlos0** [comment]
I thought about this, I think the flags are more versatile, as we can easily use them for generated headers/footers as well...

I get why you are doing it on config as well, I suggest you fix them in your CI config instead...  even something like `--release-footer <(echo "my simple footer")` should work if you don't want to create the files.

Will close this for now, thanks for the contribution anyway :)

**Pull request closed without merging**
