### PR TITLE
WIP: feat: add github action

### PR DESCRIPTION
**Pull request by fallion**
If applied, this commit will allow for using goreleaser as a Github action.

### CODE REVIEW

**Comment by caarlos0** [comment]
afaik this will not work, as our dockerfile depends on the goreleaser build...

the current documented way (using the docker image directly) is not working?

**Comment by fallion** [comment]
Ah. I wanted to make it nicer to use with Github actions.

**Comment by fallion** [comment]
I'll try testing this in another repo if I can make it work.

**Comment by fallion** [comment]
Closed as current way works better :)

**Pull request closed without merging**
