### PR TITLE
nfpm: added termux

### LINKED ISSUE #3118: termux
### Is your feature request related to a problem? Please describe.

Isn't #1310 fairly easy now with [nfpm](https://github.com/goreleaser/nfpm)?
Tried a `deb` build with different `bindir` and could install it successfully with `dpkg --force-all` (was just complaining about achitecture not being specified as `aarch64`).

### Describe the solution you'd like

Termux config or ability to set architecture name for deb file. Maybe not even needed and was just sth. related to installing it with `dpkg` instead of `pkg`. Ideally just needs documentation.

### Describe alternatives you've considered

Configuring a second `nfpm` build:
```yaml
    id: termux
    formats:
      - deb
    file_name_template: "{{ .ConventionalFileName }}_termux"
    bindir: /data/data/com.termux/files/usr/bin
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rsteube**
fix #3118

### CODE REVIEW

**Comment by rsteube** [comment]
The `arm64/aarch64` version installed without error on my phone.

**Review by caarlos0 — COMMENTED** [review]
this looks ok, but needs testing

would also be cool to clarify in the docs what termux.deb does differently...

**Comment by caarlos0** [comment]
judging by this: https://packages.termux.dev/apt/termux-main/dists/stable/main/

it seems arm, arm64, 386 and amd64 are supported... will make the needed changes...

**Comment by rsteube** [comment]
Ah, yes. Just couldn't imagine a device still using `386`.

**Pull request closed without merging**
