### PR TITLE
Fix go-macaron/cors revision issue

### PR DESCRIPTION
**Pull request by chenrui333**
Relates to https://github.com/Homebrew/homebrew-core/pull/44526

```
22:45:54 chmod -Rf +w /private/tmp/d20190924-15630-93f5qe
22:45:54 ==> go mod vendor
22:45:54 go: code.gitea.io/gitea@v1.10.0-dev.0.20190711052757-a0820e09fbf7 requires
22:45:54 github.com/go-macaron/cors@v0.0.0-20190309005821-6fd6a9bfe14e9: invalid pseudo-version: revision is longer than canonical (6fd6a9bfe14e)
22:45:54
```

### CODE REVIEW

**Comment by caarlos0** [comment]
conflicts 🤔

**Comment by tpounds** [comment]
@caarlos0, @chenrui333 FYI looks like the conflict is a result of the same fix being merged in https://github.com/goreleaser/goreleaser/pull/1155.

**Comment by chenrui333** [comment]
I was not aware of that change.

**Comment by chenrui333** [comment]
Oh, I see, that PR was filed after mine. (should not we merge PR in sequence? :) )

**Comment by chenrui333** [comment]
As the fix is in place, closing the PR now.

**Comment by caarlos0** [comment]
yeah, looks like...

**Comment by caarlos0** [comment]
thanks everyone btw 🚀

**Comment by chenrui333** [comment]
Yeah, glad it works out though!

**Pull request closed without merging**
