### PR TITLE
fix: add env to the sign schema

### PR DESCRIPTION
**Pull request by cpanato**
- schema: add env to the sign schema

/assign @caarlos0

### CODE REVIEW

**Comment by caarlos0** [comment]
oh, this should have been auto-gen... 

thanks anyway!

**Comment by cpanato** [comment]
hum, where to check why was not generated?

**Comment by caarlos0** [comment]
its on the pro fork only because it has extra flags, will need to move some stuff around

**Comment by caarlos0** [comment]
done in f545fee

**Pull request merged**
