### PR TITLE
Custom release file

### PR DESCRIPTION
**Pull request by caarlos0**
refs #183 

The user should now be able to run `goreleaser --release-notes /blah/notes.md` or even use some changelog generator or custom commands, like `goreleaser --release-notes <( some-changelog-generator )`.

Also:

- removed the previous tag from the context because it was not used outside;
- moved release body generation to the release pipe instead of the clients pkg;
- added some TODOs.

### CODE REVIEW

**Comment by caarlos0** [comment]
cc/ @bep

**Comment by bep** [comment]
This is exactly what I (we) need. Thanks.

**Comment by caarlos0** [comment]
@bep nice, will merge!

**Comment by bep** [comment]
@caarlos0 This works very good, btw -- see my test here:

https://github.com/bep/hugo/releases/tag/v0.20.6

Of course, I still have some work on my side before it is good to go ...

**Comment by caarlos0** [comment]
Nice @bep , glad it worked!

**Pull request merged**
