### PR TITLE
feat: docker link for extra folders

### PR DESCRIPTION
**Pull request by caarlos0**
## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] I have read the **CONTRIBUTING** document.
* [ ] `make ci` passes on my machine.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

I've made the following changes and tested it in goreleaser itself as well:

```patch
diff --git a/.goreleaser.yml b/.goreleaser.yml
index eee494f..c4a269d 100644
--- a/.goreleaser.yml
+++ b/.goreleaser.yml
@@ -5,12 +5,8 @@ builds:
     goos:
       - linux
       - darwin
-      - windows
     goarch:
-      - 386
       - amd64
-      - arm
-      - arm64
 checksum:
   name_template: '{{ .ProjectName }}_checksums.txt'
 changelog:
@@ -24,6 +20,10 @@ dockers:
   - image: goreleaser/goreleaser
     latest: true
     tag_template: '{{ .Tag }}'
+    extra_files:
+    - config/testdata
+    - config
+    - README.md
 archive:
   name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
   replacements:
@@ -50,9 +50,6 @@ fpm:
   maintainer: Carlos Alexandro Becker <root@carlosbecker.com>
   license: MIT
   vendor: GoReleaser
-  formats:
-    - deb
-    - rpm
   dependencies:
     - git
 snapcraft:
@@ -63,4 +60,4 @@ snapcraft:
     wrapped in your favorite CI.
   grade: stable
   confinement: classic
-  
\ No newline at end of file
+
diff --git a/Dockerfile b/Dockerfile
index b7dcde4..217c0ea 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,4 +1,7 @@
-FROM scratch
+FROM alpine
 COPY goreleaser /goreleaser
-ENTRYPOINT ["/goreleaser"]
+ADD testdata testdata
+ADD README.md /
+ADD config /config
+# ENTRYPOINT ["/goreleaser"]
 ```

so I `go run main.go --skip-validate --skip-publish --rm-dist` and `docker run -it goreleaser/goreleaser:latest /bin/sh`, checking if the image was correct, and indeed it was.

This is a "simpler"  implementation of #483.

closes #483

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e4da87b2620b5d2d86833f6dd6e152c0d27f0b42
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: cdc306a31076d33bbfb35cd9d0494d19dfaae51c
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by caarlos0** [comment]
@slot can you take a look?

**Comment by slot** [comment]
Hey @caarlos0, very elegant solution with filepath walk. Do we need to avoid infinite loops if someone wants to include `dist` for instance or the full project root?

**Comment by caarlos0** [comment]
> Hey @caarlos0, very elegant solution with filepath walk. Do we need to avoid infinite loops if someone wants to include dist for instance or the full project root?

makes sense...

**Pull request merged**
