### PR TITLE
WIP: fix: use the right sha256 sum on archive releases

### LINKED ISSUE #686: Wrong sha256 used in Brew Forumula generation
**Describe the bug**

goreleaser is using the `darwin_amd64.tar.gz` sha256 instead of the one for the source.

**To Reproduce**

```yaml
builds:
  - binary: saw
    goos:
      - darwin
      - linux
      - freebsd
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 6
      - 7

archive:
  format: tar.gz
  files:
    - LICENSE

brew:
  name: saw

  github:
    owner: TylerBrock
    name: homebrew-saw

  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy

  commit_author:
    name: TylerBrock
    email: <redacted>

  folder: Formula
  homepage: "https://github.com/TylerBrock/saw"
  description: "Fast, multipurpose tool for AWS CloudWatch Logs"

  build_dependencies:
    - go
    - dep

git:
  short_hash: true
```

I'm generating a formula for my project called Saw. It works fine then I add the tap and install the formula but then it says it expects the sha256 to be the darwin one instead of the one for the source tarball.

```sh
$ brew tap TylerBrock/saw
...
$ brew install saw
==> Installing saw from tylerbrock/saw
==> Downloading https://github.com/TylerBrock/saw/archive/v0.1.2.tar.gz
==> Downloading from https://codeload.github.com/TylerBrock/saw/tar.gz/v0.1.2
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: f7398ea54c80befe994f898010c21ef9a62c880c2f25a9ac2bf84765a09b5313
Actual: bfdf5988554276327544eb8fea3943792ac63bfbe0d558bc1ef65d105b6764f3
Archive: /Users/tbrock/Library/Caches/Homebrew/saw-0.1.2.tar.gz
To retry an incomplete download, remove the file above.
```

This is what the generated formula looks like:

```rb
class Saw < Formula
  desc "Fast, multipurpose tool for AWS CloudWatch Logs"
  homepage "https://github.com/TylerBrock/saw"
  url "https://github.com/TylerBrock/saw/archive/v0.1.2.tar.gz"
  head "https://github.com/TylerBrock/saw.git"
  version "0.1.2"
  sha256 "f7398ea54c80befe994f898010c21ef9a62c880c2f25a9ac2bf84765a09b5313"
  depends_on "go" => :build
  depends_on "dep" => :build

  def install
    bin.install "saw"
  end
end
```

So of course this is not-working because it's writing the formula with the darwin_amd64 sha256 rather than the one for the source tar.gz (which is the file it requests via `url`).

```sh
$ gsha256sum saw_0.1.2_darwin_amd64.tar.gz
f7398ea54c80befe994f898010c21ef9a62c880c2f25a9ac2bf84765a09b5313  saw_0.1.2_darwin_amd64.tar.gz
$ gsha256sum saw-0.1.2.tar.gz
bfdf5988554276327544eb8fea3943792ac63bfbe0d558bc1ef65d105b6764f3  saw-0.1.2.tar.gz
```

**Expected behavior**

I'd expect for it to use the sha starting with `bfdf59...` in the formula.

**Environment (please complete the following information):**

- OS: Mac OS X
- OS version: Sierra 10.13.4
- GoReleaser Version 0.77.0

**Additional context**

### PR DESCRIPTION
**Pull request by caarlos0**
closes #686

I particularly don't like the way I did this... will think mroe about it and give another try later.

### CODE REVIEW

**Comment by TylerBrock** [comment]
Thank you for jumping on this so quickly!

**Comment by caarlos0** [comment]
> Thank you for jumping on this so quickly! Do a lot of people use this functionality? It's really great.

I think 99.9% of people are using the tap only...

**Comment by TylerBrock** [comment]
Oh, I’m using the tap. That’s the bit that isn’t working. Maybe I’m using it incorrectly but I thought the idea is that you have a repo that hosts your tap at: <username>/homebrew-<projectname>

The benefit of this is that your project is immediately tappable by homebrew which builds your project from source (does not use the prebuilt Darwin binary).

Is there another mode?

**Comment by TylerBrock** [comment]
Ah, I think I understand. When you add `build_dependencies` that triggers goreleaser to create a formula which builds from source rather than using the pre-built binaries.

The part that was tripping me up is that either way can be a tap or part of core.

**Comment by caarlos0** [comment]
@TylerBrock yeah, that's right!

If you add the build dependencies section, it tries to build from source, which is currently broken.

I'm working on other things now, will try to look into this during this week...

If you want to deliver as tap, you can just remove the build_dependencies part and it should work :)

**Comment by TylerBrock** [comment]
It works great. Thank you, this software is incredible and saved me countless hours.

**Comment by caarlos0** [comment]
Hi @TylerBrock 

Nice to hear that!

Yes, you can donate through opencollective -> https://opencollective.com/goreleaser

Thanks for the appreciation! 🍻

**Pull request closed without merging**
