### PR TITLE
feat: Add Prerelease flag

### PR DESCRIPTION
**Pull request by dominikschulz**
This PR adds a prerelease flag to create prereleases on GitHub without any need to edit the config.

I'll add tests and documentation if you like the general idea of this PR.

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [x] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [x] I have read the **CONTRIBUTING** document.
* [ ] `make ci` passes on my machine.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6f73863e832ea4eae141d9f69b3c1334e0298c63
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6f73863e832ea4eae141d9f69b3c1334e0298c63
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: d97c1663495066351e1b932c2a728fc116e0862f
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by caarlos0** [comment]
the problem with this is that we would also need to implement some sort of continue, otherwise running with the flag and then without it would have "weird" behavior. 

By weird, I mean that I don't know what the obvious thing to do in that case, possibly other users wouldn't know as well...

Not sure if this will be a good addition...

**Comment by dominikschulz** [comment]
We've successfully used this to issue prereleases on GitHub. Why would you need to continue afterwards? You can just issue a regular release when you're ready?

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 72454aa5d67a4afe3cc3c1b9f3555ee52882f8b7
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by caarlos0** [comment]
so, what is the process?

create a pre-release, if OK, promote it? 

or is it just like an alpha release that keeps as pre-release forever?

**Comment by dominikschulz** [comment]
It's rather like an alpha release. This benefit of the prerelease flag is that they are marked as such on the GitHub release pages and you usually don't want to push homebrew updates or other kind of packages out for such releases. This flag enables this workflow.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cea96827d4d5ef9158ec4e0253a997eab5f0a78f
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 4c2cf0b63e67d0882d116d48b85a66f707400c20
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cea96827d4d5ef9158ec4e0253a997eab5f0a78f
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by caarlos0** [comment]
@dominikschulz maybe #667 is a better idea?
What do you think?

**Comment by dominikschulz** [comment]
Yes, that's even better than my proposal! I'm all in favor or #667 :+1:

**Comment by caarlos0** [comment]
nice, I'll close this one then.

Will work on that this week!

Thanks @dominikschulz !

**Pull request closed without merging**
