### PR TITLE
Support for "Store all of your packages in one GitLab project"

### PR DESCRIPTION
**Pull request by tinboxw**
Support for "Store all of your packages in one GitLab project"(see https://docs.gitlab.com/ee/user/packages/workflows/project_registry.html). Add a configuration option package_registry_project: "project_id or project_name" to specify the project name for the packages registry

...

...

...

### CODE REVIEW

**Comment by caarlos0** [comment]
I think that should go in `release.gitlab` instead of gitlab urls 🤔

**Comment by tinboxw** [comment]
> I think that should go in `release.gitlab` instead of gitlab urls 🤔

Assuming my GitLab repository includes the following **private** projects: `git.test.com/test/a`, `git.test.com/test/b`, `git.test.com/test/c`. Without any special handling, the software packages released by projects `a/b/c` will be stored in their own package registries.

Now, I've introduced a **public** project: `git.test.com/test/version`, which is used to store software packages.

So now, I need to specify a new package registry address in the `.goreleaser.yaml` files of `a/b/c`.

However, if I modify `release.gitlab` to the project ID of `version` (for example: **49**) in project a, it will affect the name of the entire project a (the built-in variable `{{ .ProjectName }}` will also be changed to **49**); so there needs to be a separate configuration to set the project ID or name of the **git.test.com/test/version** repository.

i modify `release.gitlab` config:
```
archives:
  - format: tar.gz
    name_template: >-
      obts_
      {{- if index .Env "PRODUCT_VERSION"  }}{{ .Env.PRODUCT_VERSION }}{{- else }}1.0.0{{ end }}_
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- tolower .Os }}_
      {{- if eq .Arch "amd64" }}amd64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}_
      {{- time "20060102" }}
      {{- if .IsSnapshot }}_devel{{ end }}
   ...

release:
  gitlab:
    name: "49"
  mode: replace
```

the {{.ProjectName}} is changed(**49**) in log(include `checksums/*.tar.gz/*zip`) :
```
  • archives
    • creating                                       archive=a.output/obts_1.0.0_49_0.3.0_linux_amd64_20240310.tar.gz
    • creating                                       archive=a.output/obts_1.0.0_49_0.3.0_windows_amd64_20240310.zip
    • took: 1s
  • calculating checksums
  • publishing
    • scm releases
      • creating or updating release                 tag=0.3.0 repo=
      • refreshing checksums                         file=49_0.3.0_checksums.txt
      • release updated                              name=0.3.0
      • uploading to release                         file=a.output/49_0.3.0_checksums.txt name=49_0.3.0_checksums.txt
      • uploading to release                         file=a.output/obts_1.0.0_49_0.3.0_linux_amd64_20240310.tar.gz name=obts_1.0.0_49_0.3.0_linux_amd64_20240310.tar.gz
      • uploading to release                         file=a.output/obts_1.0.0_49_0.3.0_windows_amd64_20240310.zip name=obts_1.0.0_49_0.3.0_windows_amd64_20240310.zip
      • published                                    url=https://git.ibrifuture.com//49/-/releases/0.3.0
      • took: 21s
  • took: 21s
  • storing release metadata
    • writing                                        file=a.output/artifacts.json
    • writing                                        file=a.output/metadata.json
  • announcing
  • release succeeded after 2m18s
  • thanks for using goreleaser!
```

**Comment by caarlos0** [comment]
I think then you need to set `project_name` in your goreleaser.yml as well, this way it will not try guess based on other configurations

**Comment by caarlos0** [comment]
closing as per my last comment

**Pull request closed without merging**
