### PR TITLE
feat: Changelog customization

### PR DESCRIPTION
**Pull request by caarlos0**
## Types of changes

- [x] New feature (non-breaking change which adds functionality)
- [x] I have read the **CONTRIBUTING** document.
- [x] `make ci` passes on my machine.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by jorinvo** [comment]
> I turned myself into a pipe morty!
> 
> PipeRick!!!
 
😄 
`changelog.filters.excludes` as a regex looks like a good and simple solution to me. It should solve the majority of cases and otherwise people can still create their own file from scratch.

**Comment by caarlos0** [comment]
> changelog.filters.excludes as a regex looks like a good and simple solution to me. It should solve the majority of cases and otherwise people can still create their own file from scratch.

@jorinvo done

**Comment by jorinvo** [comment]
Nice! Should merge this. Then we can also use it for the changelog of GoReleaser itself :)

**Comment by tj** [comment]
piperick!

**Pull request merged**
