### PR TITLE
fix: getTag return incorrect tag, if we have more than 1 tag for 1 commit

### PR DESCRIPTION
**Pull request by andriisoldatenko**
Possible fix of https://github.com/goreleaser/goreleaser/issues/1163

### CODE REVIEW

**Comment by caarlos0** [comment]
build is failing...

**Comment by andriisoldatenko** [comment]
@caarlos0 fixed.

**Comment by caarlos0** [comment]
awesome, thanks!

**Comment by caarlos0** [comment]
will need to revert this, check #1211

**Comment by andriisoldatenko** [comment]
@caarlos0 checking...

**Pull request merged**
