### PR TITLE
Draft: feat: allow default branch to be used in Gitlab CreateFile

### PR DESCRIPTION
**Pull request by drewstinnett**
This commit will look up the default branch name in the Gitlab project, and if it can't find one, fall back to `master`, when using the CreateFile function

Previously, the branch used in CreateFile for Gitlab operations was hard coded to `master`. Now that Gitlab has switched over to `main` as the default branch, things like brew publishing breaks since the `master` branch doesn't exist. 

There isn't currently a test in place for any of the CreateFile stuff in `gitlab_test.rb`, so not sure what to do there...open to ideas though!

https://about.gitlab.com/blog/2021/03/10/new-git-default-branch-name/

Thanks for the consideration of this patch, and definitely open to changes/suggestions/etc!

### CODE REVIEW

**Comment by caarlos0** [comment]
we have https://github.com/goreleaser/goreleaser/issues/2388 

I think we could allow to pass the branch, and get the default only if its empty. That's for all impls (gitlab, github and gitea)

wdyt?

**Comment by drewstinnett** [comment]
Ahhh I had not realized these were the same, good point! Yes, that makes a lot of sense here. I'd be happy to adjust the PR to use the behavior described above and in #2388! If it's cool with you, I'll adjust the MR later today (or maybe later this week, depending on time haha)

**Comment by caarlos0** [comment]
sure thing! thanks so much @drewstinnett 🙏

btw, let me know if you need help on anything, I'm usually on gophers slack and also on our discord server 👌

**Comment by drewstinnett** [comment]
Def will, ty @caarlos0, you rock!

**Comment by caarlos0** [comment]
I would say that, to simplify, we could leave out the create branch thing...

- if config branch is empty, use default branch
- otherwise, use the branch provided, regardless of wether it exists or not

that way, if the user introduces a typo (e.g. `maste` instead of `master`), the error won't be "silenced"... 


also, to get the default branch on github: https://pkg.go.dev/github.com/google/go-github/v39/github#Repository.GetDefaultBranch

gitea seems to have it as well: https://pkg.go.dev/code.gitea.io/sdk/gitea#Repository

**Comment by drewstinnett** [comment]
Ahhh good call, will adjust!

**Comment by drewstinnett** [comment]
Okey doke, removed the `CreateBranch` stuff, and added the `GetDefaultBranch`, along with some tests to Github and Gitea (in addition to the one that's in there already for Gitlab)

Happy to adjust as needed, and ty for the consideration!

**Comment by caarlos0** [comment]
Amazing! Thanks you!

**Pull request merged**
