### PR TITLE
refactor: use git tag --points-at

### LINKED ISSUE #1793: Use git tag --points-at to detect the legitimate tag
@caarlos0 

Refs. goreleaser/goreleaser-action#238 goreleaser/goreleaser-action#239

As explained on Slack, I think `git describe` is (maybe) not a good way to detect the "proper" tag. We should first use [git tag --points-at](https://git-scm.com/docs/git-tag#Documentation/git-tag.txt---points-atltobjectgt) to detect the legitimate latest tag if a commit has multi tags (sort by `-version:creatordate`). If none is found/valid then we can use `git describe --tags --abbrev=0`.

You can find an implementation in [our GitHub Action](https://github.com/goreleaser/goreleaser-action/blob/097bb3c0c5b5249fdc72ccdff0f874aebdc93839/src/git.ts#L12-L31).

### PR DESCRIPTION
**Pull request by caarlos0**
closes #1793

is this what you meant @crazy-max?

### CODE REVIEW

**Comment by crazy-max** [comment]
@caarlos0 Yes pretty much but `git tag --points-at` can return a [list of tags](https://github.com/goreleaser/goreleaser-action/blob/master/src/git.ts#L25).

**Comment by caarlos0** [comment]
yeah, `git.Clean` takes the first line of STDOUT only... so.. it should be fine I think 🤔

**Review by crazy-max — APPROVED** [review]
Oh ok I missed that. LGTM then!

**Comment by caarlos0** [comment]
thanks @crazy-max 🙏

**Pull request merged**
