### PR TITLE
chore(deps): bump code.gitea.io/sdk/gitea from v0.12.1 to v0.13.0

### PR DESCRIPTION
**Pull request by 6543**
<details>
<summary>Changelog</summary>
<br>
<b>BREAKING</b><br>
  * Check Gitea Version Requirement (#419)<br>
  * All Function return http responce (#416)<br>
  * Remove opts from ListPullReviewComments (#411)<br>
  * Use enum AccessMode for OrgTeam and Collaborator functions (#408)<br>
  * CreateOrgOption rename UserName to Name (#386)<br>
  * EditMilestoneOption also use StateType (#350)<br>
  * Refactor RepoSearch to be easy usable (#346)<br>
<b>FEATURES</b><br>
  * Milestone Functions accept name to identify (#418)<br>
  * Make http requests with context (#417)<br>
  * Add GetGlobalAttachmentSettings (#414)<br>
  * Add GetArchive (#413)<br>
  * Add GetRepoLanguages + TESTs (#412)<br>
  * Add CreateBranch (#407)<br>
  * Add Admin CronTask functions (#406)<br>
  * Add GetGlobalAPISettings Function (#404)<br>
  * Add Get Diff and Patch endpoints for pull requests (#398)<br>
  * Add Validate func for Create/Edit Options (#370)<br>
  * Add Function to get GetGlobalSettings and GetSettingAllowedReactions (#359)<br>
<b>ENHANCEMENTS</b><br>
  * TrackedTime API >= 1.11.x needed (#415)<br>
  * Update Milestone struct (#410)<br>
  * Add Fallback for GetPullRequestDiff/Patch (#399)<br>
  * DeleteToken Accept Names too (#394)<br>
  * Update ListMilestoneOption struct (#393)<br>
  * Migration Api Changed (#392)<br>
  * Refactor Visibletype Orgs (#382)<br>
  * Extend Notification Functions (#381)<br>
  * Update GetGlobalSettings Functions (#376)<br>
  * Allow Creating Closed Milestones (#373)<br>
  * CreateLabel correct Color if needed for old versions (#365)<br>
  * Issue/Pull add IsLocked Property (#357)<br>
  * Update EditPullRequestOption Add Base (#353)<br>
  * File Create/Update/Delete detect DefaultBranch if Branch not set for old Versions (#352)<br>
  * Improve Error Handling (#351)<br>
</details>

[Migration Guide](https://gitea.com/gitea/go-sdk/src/branch/master/docs/migrate-v0.12-to-v0.13.md)

## This Pull does

* update to v0.13.0
* migrate
* adapt new features

close #1794

### CODE REVIEW

**Comment by 6543** [comment]
@caarlos0 you might have a look at it

**Comment by caarlos0** [comment]
Thanks!

**Comment by caarlos0** [comment]
@6543 had to revert, didn't see tests were failing...

**Comment by 6543** [comment]
sadly ... but I fond a you a bug I think is related to this

**Comment by 6543** [comment]
I'll prepare a new one - hope it will do it this time!

**Comment by 6543** [comment]
throu I'll wait for 1. October for Hacktoberfeest if this is ok?

**Pull request merged**
