### PR TITLE
chore(deps): cleanup go.mod file

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by caarlos0** [comment]
so, downgrade the cors lib?

**Comment by chenrui333** [comment]
`github.com/go-macaron/cors` is indirect dependedncy, and I did not see the code reference in the repo.

To my memory, that was the issue when doing `go mod tidy` before (and the dependency problem with `code.gitea.io/gitea`)

Also, I think it is indrect dependency of `code.gitea.io/gitea@v1.10.0-dev`

**Comment by caarlos0** [comment]
oh yah, you're right.

thanks! 🚀

**Comment by caarlos0** [comment]
@chenrui333 check #1218

**Comment by chenrui333** [comment]
Interesting, I did not have the same error in my local though.

**Comment by chenrui333** [comment]
I switched back to go1.13, and the issue does pop up. I will submit a dependabot issue on this matter.

**Comment by chenrui333** [comment]
@caarlos0 Just reported an issue.

**Comment by caarlos0** [comment]
Thanks @chenrui333 ! :)

**Comment by ldez** [comment]
It's still the same problem that I fixed in https://github.com/goreleaser/goreleaser/pull/1138

**Comment by caarlos0** [comment]
IMHO if it works on go1.13 only, its fine.

we just need to change the docs https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md

**Comment by ldez** [comment]
The `replace` allow to use go1.12 and go1.13.

So, for me this PR must be reverted.

**Comment by chenrui333** [comment]
I am little bit confused on why need to support both go 1.12 and go 1.13? This is more like a developer-oriented tool and we should constantly keep it using the latest go offering.

**Comment by caarlos0** [comment]
> The `replace` directive is required by go1.13

does not seem to be, hence the build passing on go 1.13 🤔

**Comment by chenrui333** [comment]
I think the build passed, right?
https://travis-ci.org/goreleaser/goreleaser/builds/603598848

The dependabot PR build issue is indeed concerning, but I think that sounds like they need to do the environment update on their end, still waiting for their response on this though.

**Comment by ldez** [comment]
The `replace` directive is required by go1.13: to be precise `go mod tidy` in go1.13 required the `replace` directive

**Comment by ldez** [comment]
The CI need to validate the `go.mod` and `go.sum`

A quick way to validate that:

```
go mod tidy
git diff --exit-code go.mod
git diff --exit-code go.sum
go mod download
```

**Comment by caarlos0** [comment]
CI does that already: 

- https://github.com/goreleaser/goreleaser/blob/master/.travis.yml#L17
- https://github.com/goreleaser/goreleaser/blob/master/Makefile#L52
- https://github.com/goreleaser/goreleaser/blob/master/Makefile#L45-L49

**Comment by chenrui333** [comment]
@ldez I believe it passed CI, it is just the dependabot environment needs to be updated to use latest golang. I works on go v1.13.3 but not v1.13 though.

**Comment by ldez** [comment]
I use go 1.13.13 and I need to set the `replace` directive to get an error:

```console
$ go version
go version go1.13.3 linux/amd64

$ go mod tidy
go: code.gitea.io/gitea@v1.10.0-dev.0.20190711052757-a0820e09fbf7 requires
        github.com/go-macaron/cors@v0.0.0-20190309005821-6fd6a9bfe14e9: invalid pseudo-version: revision is longer than canonical (6fd6a9bfe14e)
```

**Comment by chenrui333** [comment]
let me re-check. :)

**Comment by ldez** [comment]
@caarlos0 I find the tricks:

```
export GOPROXY = https://proxy.golang.org,https://gocenter.io,direct
```

I think that `https://gocenter.io` give the invalid hash.

**Comment by chenrui333** [comment]
Good finding. Isn't the default goproxy goes to `https://proxy.golang.org`?

**Comment by ldez** [comment]
It's a fallback system: https://proxy.golang.org > https://gocenter.io > direct

**Comment by chenrui333** [comment]
That is right

**Comment by ldez** [comment]
I confirm: the problem come from https://gocenter.io

https://proxy.golang.org/github.com/go-macaron/cors/@v/v0.0.0-20190309005821-6fd6a9bfe14e9.info

https://search.gocenter.io/github.com~2Fgo-macaron~2Fcors/info?version=v0.0.0-20190309005821-6fd6a9bfe14e9

**Comment by caarlos0** [comment]
cc/ @ankushchadha

**Comment by elioengcomp** [comment]
Version `v0.0.0-20190309005821-6fd6a9bfe14e9` works fine to previous versions of Go even though it has 13 digits for the commit hash part instead of the expected 12. Go 1.12 seems not to care

**Comment by elioengcomp** [comment]
Version `v0.0.0-20190309005821-6fd6a9bfe14e9` works fine to previous versions of Go even though it has 13 digits for the commit hash part instead of the expected 12. Go 1.12 seems not to care about it:

```
→ go get github.com/go-macaron/cors@v0.0.0-20190309005821-6fd6a9bfe14e9

go: finding github.com/go-macaron/cors v0.0.0-20190309005821-6fd6a9bfe14e9
go: finding github.com/go-macaron/inject v0.0.0-20160627170012-d8a0b8677191
go: finding gopkg.in/ini.v1 v1.42.0
```

**Comment by ldez** [comment]
go1.12 don't use `https://proxy.golang.org` as `GOPROXY` by default.
go1.13 use `https://proxy.golang.org` as `GOPROXY` by default.

If you use go1.12 and `GOPROXY=https://proxy.golang.org` the behavior is very close.

The problem comes because the date `20190309005821` is not the valid date for `6fd6a9bfe14e9` and the hash size problem (13 instead 12)

**Comment by elioengcomp** [comment]
> This PR do the inverse: use v0.0.0-20190309005821-6fd6a9bfe14e9 instead of a valid pseudo version.

Sorry, my mistake. We should move to the latest version of the dependency instead.

**Comment by ldez** [comment]
`github.com/go-macaron/cors` is a dependency of  'code.gitea.io/sdk/gitea` that does not contain any semver version.

I fixed the problem.

**Pull request merged**
