### PR TITLE
feat: AUR source integration

### LINKED ISSUE #5278: Support Sources AUR (!= archlinux format)
### Is your feature request related to a problem? Please describe.

I know there is the `archlinux` format for `nfpms`.

EDIT: I removed the previous description because I was misled by my own commit message error... Sorry.

### Describe the solution you'd like

Currently, only pre-compiled packages (`-bin`) are supported.

I think it's possible to use the [source archive](https://goreleaser.com/customization/source/) to create a package from sources.

As a user should respect the difference between `-bin` or not, I think a new "type" can be introduced to be sure that only sources are used in this context.

Something like that:

```yml
aurs:
  -
    git_url: "ssh://aur@aur.archlinux.org/foo-bin.git"
    # ...
  -
    git_url: "ssh://aur@aur.archlinux.org/foo.git"
    type: "source"
    # ...
```

```go
ctx.Artifacts.Filter(artifact.ByType(artifact.UploadableSourceArchive))
```

Also, some extra configurations can be required:

```yml
aurs:
  -
    git_url: "ssh://aur@aur.archlinux.org/foo.git"
    type: "source"
    # ...
    makedepends: ...
    prepare: ...
    build: ...
    package: ...
```

ref: https://wiki.archlinux.org/title/Creating_packages

This is just a raw idea, and I don't know the architecture of goreleaser, maybe there is a better way than the `type` field.

### Describe alternatives you've considered

Uses `archlinux` format?

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

To be able to publish automatically [nfpm](https://aur.archlinux.org/packages/nfpm) and [nfpm-bin](https://aur.archlinux.org/packages/nfpm-bin).

### PR DESCRIPTION
**Pull request by ldez**
This PR allows to publish AUR based on sources (not binaries)

This is more a draft than a final version (even if the implementation is completed):  I think showing the differences with the "aur-bin" is easier.

Most of the code is a copy of the "aur-bin" implementation.
But there are multiple differences.

The name is `aursources` but I have some doubts about that.

Fixes #5278

### CODE REVIEW

**Review by caarlos0 — APPROVED** [review]
looking good so far

**Comment by ldez** [comment]
Do you want me to change anything?
Name `aur_sources` is OK for you?

If there is nothing to change, the PR is ready :smile_cat:

**Comment by caarlos0** [comment]
> Name `aur_sources` is OK for you?

I don't have a better suggestion, so I think it is good :) 

I haven't tested it, but will in the coming days, code looks good to me though

**Comment by caarlos0** [comment]
thank you so much @ldez, for yet another contribution! Hope the process was good (let me know if you think it can be improved :))

**Pull request merged**
