### PR TITLE
wip: feat: multiple archives

### LINKED ISSUE #705: Create Multiple Archives
**Is your feature request related to a problem? Please describe.**
We would like to release a server/client from a single repo using goreleaser. 

**Describe the solution you'd like**
Ideally we'd be able to create multiple archives - one for the server and one for the client. When installing the client, it shouldn't be required to get the server binary as well. We should also be able to limit the number of os/arch for client/server independently.

**Describe alternatives you've considered**
We're currently using multiple builds and the client and server get packaged in every archive. 

----

Edit by @caarlos0:

- [x] add multiple archives (with everything else using `archives[0]`)
- [x] add multiple nfpm support
- [x] add multiple brew support
- [x] add multiple scoop support
- [x] add multiple snap support
- [x] add multiple http/artifactory support
- [x] add multiple s3/blob support

### PR DESCRIPTION
**Pull request by caarlos0**
Adds support to multiple archives.

The idea is that you can:

```yaml
archives:
- binaries: ['foo']
  format: 'tar.gz'
- format: zip
- binaries: ['bar']
  name_template: whatever
```

So, when `binaries` is not defined, all binaries are added. When there is some binary defined (which is the output of a build), it creates the archives with that binary only.

The same thing will be done in brew and scoop pipes - as they depend on the archives output.

---

- [x] support multiple archives
- [x] support multiple brews (for each archive for example)
- [x] support multiple scoops (for each archive for example)
- [ ] support multiple http uploads (for each archive for example)
- [ ] fix TODOs
- [ ] run "real world tests"
- [ ] update docs
- [ ] gather feedback

closes #705

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ff2594294d87dc32d912fc977044f8dff34ac204
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, add, remove, move, bump, update, release**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ff2594294d87dc32d912fc977044f8dff34ac204
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, add, remove, move, bump, update, release**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: ff2594294d87dc32d912fc977044f8dff34ac204
  * Invalid type. Valid types are **feat, fix, docs, style, refactor, perf, test, chore, revert, add, remove, move, bump, update, release**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by caarlos0** [comment]
this is proven to be way harder than previously anticipated :/

**Pull request closed without merging**
