### PR TITLE
feat: support gzip format

### PR DESCRIPTION
**Pull request by caarlos0**
refs  #958

### CODE REVIEW

**Comment by frapposelli** [comment]
wow, thanks for the super quick turnaround.

The patch works great when there's one single build, but when the builds are > 1 it tries to add the second binary to the same archive (instead of creating a new one) and fails:

```yaml
project_name: govmomi
builds:
- binary: govc
  main: ./govc/
[...]
- binary: vcsim
  main: ./vcsim/
[...]
archive:
  name_template: '{{ .Binary }}_{{ .Os }}_{{ .Arch }}'
  format: gz
  format_overrides:
    - goos: windows
      format: zip
  files:
  - none*
[...]
```

```console
govmomi · goreleaser-rehaul± ⟩ goreleaser --rm-dist --snapshot --skip-publish -p 24

   • releasing using goreleaser dev...
   • loading config file       file=.goreleaser.yml
   • RUNNING BEFORE HOOKS
   • GETTING AND VALIDATING GIT STATE
      • releasing v0.20.0, commit 2cce146648c5c7d1b85b76e48e74bc6068532f13
      • pipe skipped              error=disabled during snapshot mode
   • PARSING TAG
   • SETTING DEFAULTS
      • LOADING ENVIRONMENT VARIABLES
      • SNAPSHOTING
      • GITHUB RELEASES
      • PROJECT NAME
      • ARCHIVES
      • BUILDING BINARIES
         • you have more than 1 build setup: please make sure it is a not a typo on your config
      • LINUX PACKAGES WITH NFPM
      • SNAPCRAFT PACKAGES
      • CALCULATING CHECKSUMS
      • SIGNING ARTIFACTS
      • DOCKER IMAGES
      • ARTIFACTORY
      • S3
      • HOMEBREW TAP FORMULA
      • SCOOP MANIFEST
   • SNAPSHOTING
   • CHECKING ./DIST
      • --rm-dist is set, cleaning it up
   • WRITING EFFECTIVE CONFIG FILE
      • writing                   config=dist/config.yaml
   • GENERATING CHANGELOG
      • pipe skipped              error=not available for snapshots
   • LOADING ENVIRONMENT VARIABLES
      • pipe skipped              error=publishing is disabled
   • BUILDING BINARIES
      • building                  binary=dist/freebsd_arm_6/govc
      • building                  binary=dist/linux_amd64/govc
      • building                  binary=dist/linux_386/govc
      • building                  binary=dist/darwin_386/govc
      • building                  binary=dist/linux_arm64/govc
      • building                  binary=dist/darwin_amd64/govc
      • building                  binary=dist/linux_arm_6/govc
      • building                  binary=dist/windows_386/govc.exe
      • building                  binary=dist/windows_amd64/govc.exe
      • building                  binary=dist/freebsd_amd64/govc
      • building                  binary=dist/freebsd_386/govc
      • building                  binary=dist/freebsd_arm_6/vcsim
      • building                  binary=dist/linux_arm64/vcsim
      • building                  binary=dist/freebsd_386/vcsim
      • building                  binary=dist/windows_386/vcsim.exe
      • building                  binary=dist/freebsd_amd64/vcsim
      • building                  binary=dist/windows_amd64/vcsim.exe
      • building                  binary=dist/linux_amd64/vcsim
      • building                  binary=dist/linux_386/vcsim
      • building                  binary=dist/darwin_amd64/vcsim
      • building                  binary=dist/darwin_386/vcsim
      • building                  binary=dist/linux_arm_6/vcsim
   • ARCHIVES
      • creating                  archive=dist/govc_linux_arm64.gz
      • creating                  archive=dist/govc_darwin_386.gz
      • creating                  archive=dist/govc_freebsd_386.gz
      • creating                  archive=dist/govc_linux_386.gz
      • creating                  archive=dist/govc_darwin_amd64.gz
      • creating                  archive=dist/govc_freebsd_arm.gz
      • creating                  archive=dist/govc_windows_386.zip
      • creating                  archive=dist/govc_linux_amd64.gz
      • creating                  archive=dist/govc_windows_amd64.zip
      • creating                  archive=dist/govc_linux_arm.gz
      • creating                  archive=dist/govc_freebsd_amd64.gz
   ⨯ release failed after 10.60s error=failed to add dist/freebsd_arm_6/vcsim -> vcsim to the archive: gzip: failed to add vcsim, only one file can be archived in gz format
```

**Comment by caarlos0** [comment]
yeah, this will not be possible right now... the fix is big and will land on #705 

will add a note to the docs though

**Comment by caarlos0** [comment]
you may workaround it with multiple .goreleaser files... one for each build :)

**Comment by frapposelli** [comment]
sounds good, thanks a ton!

**Pull request merged**
