### PR TITLE
Always use latest tag as source

### PR DESCRIPTION
**Pull request by jorinvo**
This should help with #72.
As you can see from the commits I also fixed another small bug and included it here.

To clean up `git stash` and `git checkout` I added a new interface `Cleaner`. 
Please let me know if you have suggestions for a better solution.

### CODE REVIEW

**Comment by caarlos0** [comment]
It looks good, but I think it's more safe to just fail if the current ref isn't the tag ref.

Stashing and un-stashing things looks like a good idea, but the idea is that goreleaser would be integrated within the CI, so there isn't anything to stash.

If running locally, IMHO is better to alert the user that the code should not be changed and HEAD should be the tag while running goreleaser. The user might change files in another shell or editor while goreleaser is running and it will then be "wrong" anyways... 

What do you think?

**Comment by jorinvo** [comment]
Personally, I can still see the use case for running GoReleaser locally and manually. 
In this case it's really convenient to not having to switch branches and stash changes. 

I also understand the issue of the additional complexity. I guess we would need to see in practice if any problems come up.

**Comment by caarlos0** [comment]
@jorinvo yeah, ok

**Comment by caarlos0** [comment]
yeah, travis won't let we stash changes...

```
Using source from latest tag
 -> Stashing changes
failed stashing changes: 
*** Please tell me who you are.
Run
  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for <travis@testing-docker-25b1f0fa-18ec-44fb-a019-8cb8b231b923.(none)>) not allowed
Cannot save the current index state
exit status 1
```

https://travis-ci.org/goreleaser/goreleaser

**Pull request merged**
