### PR TITLE
Add instructions for using with Google CloudBuild.

### PR DESCRIPTION
**Pull request by ncabatoff**
Add instructions for running goreleaser in Google CloudBuild.

See also issue #432.

### CODE REVIEW

**Comment by caarlos0** [comment]
thanks @ncabatoff !

question: does the changelog work? If you don't have the tags, and as far as I understand, you re-create the current tag on that repo, you won't have the previous one, so the changelog will be all commits... is that right?

**Comment by ncabatoff** [comment]
Ok, so I tried removing my explicit 'git tag $TAG_NAME' from the repo where I developed these instructions, and it failed as it had in the past with "error=git doesn't contain any tags. Either add a tag or use --snapshot".  I tried add a git show-ref to the command and it only had master.  So even though the source repo mirror that's used to do the build *does* contain tags, the checkout they build from *does not*.

Having reverted my change, I can now answer your original question: it seems that goreleaser in this scenario (single tag, produced by explicit tagging with $TAG_NAME as in my PR example), creates a changelog with a single entry containing the commit message from the last commit.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: cdbb01eb57dace1f105301dcb81622e0f8f6eafe
  * Commits must be in the following format: **%{type}: %{description}**

 * Commit: 3563d61d7b1c6ec5e73b1edf85789229e73b43d9
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by caarlos0** [comment]
merged, thanks!

**Pull request merged**
