### PR TITLE
feat: implement nfpm archlinux packages

### LINKED ISSUE #3469: create arch packages
nfpm can now create arch linux packages, we should support them here as well.

will let this feature for v1.13 though, as I'm planning for v1.12 this for this weekend

### PR DESCRIPTION
**Pull request by Arsen6331**
This PR implements the Archlinux packages that were added in nfpm v2.20.0, as well as tests and documentation for them.

goreleaser/nfpm#133
goreleaser/nfpm#543
Fixes #3469

### CODE REVIEW

**Comment by Arsen6331** [comment]
The test is failing because v2.21.0 with the new code hasn't been released yet, so this will have to wait for that.

**Comment by caarlos0** [comment]
> @Arsen6331 I plan to release nfpm either tomorrow or early next week

released, and updated on goreleaser main as well 0638b0aa

**Review by caarlos0 — APPROVED** [review]
can we also add archlinux to .goreleaser.yml?

**Comment by caarlos0** [comment]
awesome, thank you @Arsen6331 ! <3

**Pull request merged**
