### PR TITLE
fix(nfpm): termux platform

### LINKED ISSUE #4809: Termux: bad system call
### What happened?

`bad system call` when executing a binary built on linux using goreleaser (or with go directly).

https://github.com/carapace-sh/carapace-bin/issues/2362

### How can we reproduce this?

Compile a binary that uses `exec.LookPath` for `arm64` on linux and try it in termux.

https://github.com/golang/go/issues/60125

### goreleaser version

```bash
____       ____      _
 / ___| ___ |  _ \ ___| | ___  __ _ ___  ___ _ __
| |  _ / _ \| |_) / _ \ |/ _ \/ _` / __|/ _ \ '__|
| |_| | (_) |  _ <  __/ |  __/ (_| \__ \  __/ |
 \____|\___/|_| \_\___|_|\___|\__,_|___/\___|_|
goreleaser: Deliver Go Binaries as fast and easily as possible
https://goreleaser.com

GitVersion:    1.22.1
GitCommit:     unknown
GitTreeState:  unknown
BuildDate:     unknown
BuiltBy:       unknown
GoVersion:     go1.21.4
Compiler:      gc
ModuleSum:     unknown
Platform:      linux/amd64

and 1.25.1 (self built)
```

### GoReleaser Check

- [X] goreleaser check shows no errors

### Search

- [X] I did search for other open and closed issues before opening this

### Supporter

- [ ] I am a [sponsor](https://github.com/sponsors/caarlos0/) or a [Pro](https://goreleaser.com/pro) customer

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Seems it just needs `GOOS=android` for the build.

### PR DESCRIPTION
**Pull request by caarlos0**
closes #4810 
closes  #4809

### CODE REVIEW

**Comment by rsteube** [comment]
@caarlos0 tried it and it works fine (can build and run the application in termux).

Btw. for the `android` build apart from `arm64` it claims that it needs cgo (not an issue, just a go requirement).

```sh
release failed after 10s                 error=failed to build for android_amd64_v1: exit status 1: android/amd64 requires external (cgo) linking, but cgo is not enabled

release failed after 8s                  error=failed to build for android_386: exit status 1: android/386 requires external (cgo) linking, but cgo is not enabled
```

Which then seems to require some android source code:
```sh
  ⨯ release failed after 18s                 error=failed to build for android_amd64_v1: exit status 1: # runtime/cgo
gcc_android.c:6:10: fatal error: android/log.h: No such file or directory
    6 | #include <android/log.h>
      |          ^~~~~~~~~~~~~~~
```

I chose to just build `arm64` on my project for now.

**Comment by rsteube** [comment]
Is this something each package needs to do?

**Comment by caarlos0** [comment]
@aicynide those seems like patches for the go programming language itself, no?

doesn't seem like something we need to do here, too.

**Comment by rsteube** [comment]
Indeed. I think I'm not affected by it but if not I'll have to use a patched go version to compile the termux package :disappointed: .

**Comment by rsteube** [comment]
Yes, we understand. But that should be related to the golang compiler being used and not goreleaser.
Termux patched the golang library directly to fix the issues related to the `resolv.conf` location.

**Pull request merged**
