### PR TITLE
feat: support additional GOOS/GOARCH targets

### PR DESCRIPTION
**Pull request by maier**
Add support for additional targets:

GOOS=illumos GOARCH=amd64
GOOS=aix GOARCH=ppc64
GOOS=android GOARCH=386
GOOS=android GOARCH=amd64
GOOS=android GOARCH=arm64
GOOS=plan9 GOARCH=arm

### CODE REVIEW

**Comment by maier** [comment]
@caarlos0 I just noticed issue 1160, I can add the remaining new GOOS/GOARCH combos from go1.13 to this PR if you'd like. (sans jswasm which you have in another PR.)

**Comment by caarlos0** [comment]
that would be awesome. I did jswasm in another pr because it needed more things (`.wasm` ext), if that's not the case with the others, feel free to do it.

FWIW will merge that PR as well.

Thanks 🚀

**Comment by caarlos0** [comment]
Thanks!

**Comment by caarlos0** [comment]
closes #1160

**Pull request merged**
