### PR TITLE
feat: homebrew: build from source

### LINKED ISSUE #342: Brew tap not accepted in homebrew-core
See: https://github.com/Homebrew/homebrew-core/pull/16943

### PR DESCRIPTION
**Pull request by caarlos0**
This PR improves the homebrew formula generation pipeline step to include additional fields that will allow building proper formula from source files than can be accepted in the core repository.

Fixes #342
Closes #621
Closes #617 

## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [ ] I have read the **CONTRIBUTING** document.
* [ ] `make ci` passes on my machine.
* [ ] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by dominikschulz** [comment]
I gave it a try and there seems to be a small whitespace issue in the template at https://github.com/goreleaser/goreleaser/pull/625/files#diff-4261e1d02d724f4bda719a39428d5e36R40 (also the golden images seem to be wrong, too).

For a real-life example see this file: https://github.com/dominikschulz/homebrew-gopass/commit/4bea075ab72b02c96e66b6c27840ea3ddf442108#diff-7bb112fb53d5546030ce1c7739ea1bc4R9

**Comment by caarlos0** [comment]
oh, indeed, thanks for pointing that out...
will fix this later today.

/remind me fix whitespace here in 8 hours

**Comment by caarlos0** [comment]
@dominikschulz should be good now

**Comment by dominikschulz** [comment]
Thanks, my test output looks good now :+1:

**Pull request merged**
