### PR TITLE
fix: typo in the git SSH command constant

### PR DESCRIPTION
**Pull request by alexandear**

### CODE REVIEW

**Comment by caarlos0** [comment]
thanks!

**Comment by caarlos0** [comment]
btw, curious, how are you finding all these typos?

**Comment by alexandear** [comment]
> btw, curious, how are you finding all these typos?

This typo I found simply be reading the code.

Other typos I spotted with [cspell](https://cspell.org/) checker that is present in VS Code.

Some typos may be found with the help of [typos-cli](https://crates.io/crates/typos-cli) or [codespell](https://github.com/codespell-project/codespell).

**Comment by caarlos0** [comment]
ah, cool! didn't know typos-cli! thanks again for all the PRs, btw 🙏🏻

**Pull request merged**
