### PR TITLE
Twitter announcer

### PR DESCRIPTION
**Pull request by leonwright**
Allow users the ability to announce via Twitter once they have completed a release.

This change was requested by owner in issue #2150 

Issue #2150

### CODE REVIEW

**Comment by caarlos0** [comment]
Looks good overall but IMHO secrets should not be in the config file... maybe allow them from env only?

**Comment by caarlos0** [comment]
about the config, maybe something like this would be better (as we could add other announcers laters):

```yaml
announce:
  twitter:
    enabled: true
    message_template: 'New {{ .ProjectName }} version is out! Get it while it's fresh: https://github.com/caarlos0/{{ .ProjectName }}'
```

Then new announcers could be another section inside announce.

Also wonder if it would make sense to allow multiple twitter instances... but I'm assuming no 🤔

**Comment by leonwright** [comment]
Thanks, I will update and revert.

**Comment by caarlos0** [comment]
completed in #2248

thanks for the work here @leonwright 🤘

**Pull request closed without merging**
