### PR TITLE
docs: tune performance and theming of documentation

### PR DESCRIPTION
**Pull request by marcauberer**
- Add support for dark mode in documentation (https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-palette-toggle)
- Use instant navigation to increase page performance

### CODE REVIEW

**Comment by caarlos0** [comment]
Veeery nice @marcauberer , thanks for the PR! 🤘

Can we enable auto-toggle based on user-preferences as well? I think we just need to add the `media` option as per their docs 🤔 

I also think that `material/lightbulb-outline` and `material/lightbulb` are easier to understand... wdyt? 🤔

**Comment by marcauberer** [comment]
Hi @caarlos0! Sounds good ... I just pushed another commit including:
- auto-toggle
- `material/lightbulb-outline` and `material/lightbulb` icons
- 'Up'-button to scroll fast

**Comment by caarlos0** [comment]
Awesome, thanks @marcauberer 🚀

**Comment by marcauberer** [comment]
Ups. Seems like the scroll button is an insider-only feature

**Comment by caarlos0** [comment]
Thanks again @marcauberer :)

**Pull request merged**
