### PR TITLE
Reduce the number of concurrent builds

### PR DESCRIPTION
**Pull request by bep**
With many GOOS OARCH combos, the CPU gets glowing.

### CODE REVIEW

**Comment by caarlos0** [comment]
Thanks!

**Comment by arran4** [comment]
Anyway to change this number?

**Comment by jorinvo** [comment]
@arran4 currently no. Can I ask for the reason why you like to change it?

**Comment by arran4** [comment]
Build exceeds memory on my machine when n is greater than 1. (16gb)

**Pull request merged**
