### PR TITLE
feat: docker - added linker for extra directories

### PR DESCRIPTION
**Pull request by slot**
## Types of changes

* [ ] Bug fix (non-breaking change which fixes an issue)
* [X] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to change)
* [X] I have read the **CONTRIBUTING** document.
* [X] `make ci` passes on my machine.
* [X] My change requires a change to the documentation.
* [ ] I have updated the documentation accordingly.
* [X] I have added tests to cover my changes.

When adding extra files to docker using a hard link it is impossible
to add a directory because only files can be linked hard. For directories
I added a linker that recursively linkes all files in a directory and re-
creates the directory structure in the dist directory.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e4da87b2620b5d2d86833f6dd6e152c0d27f0b42
  * Your commit message body contains a line that is longer than 72 characters

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: e4da87b2620b5d2d86833f6dd6e152c0d27f0b42
  * Your commit message body contains a line that is longer than 72 characters

 * Commit: cdc306a31076d33bbfb35cd9d0494d19dfaae51c
  * Commits must be in the following format: **%{type}: %{description}**

Guidelines are available at https://github.com/goreleaser/goreleaser/blob/master/CONTRIBUTING.md#create-a-commit

---
This message was auto-generated by https://gitcop.com

**Comment by caarlos0** [comment]
hey @slot thanks for the PR, I'm on vacations but will try to review this tomorrow :)

**Comment by caarlos0** [comment]
I think a better way of doing this is by using `filepath.Walk`.

Let me hack this together real quick to test it

**Comment by caarlos0** [comment]
@slot check #484

**Pull request closed without merging**
