### PR TITLE
docs: blog

### LINKED ISSUE #3503: move blog to our website
Right now, we are hosting our blog on Medium. 

I was never a big fan of it, tbh, and we're giving them some money monthly to post only sporadically... I would much rather use the new [mkdocs material blog features][mkdocs] if possible, and give that money to the mkdocs maintainer 😅

[mkdocs]: https://squidfunk.github.io/mkdocs-material/blog/2022/09/12/blog-support-just-landed/

refs #3502 

---

migration process

- [x] all announcements posts
- [x] blog migration post on the new blog
- [x] blog migration post on medium
- [x] https://blog.goreleaser.com/fast-and-furious-building-oci-compatible-container-images-with-goreleaser-and-ko-77d9378c4130
- [x] https://blog.goreleaser.com/releasing-multi-platform-container-images-with-goreleaser-in-azure-devops-d8916df4250a
- [x] https://blog.goreleaser.com/nightly-builds-with-goreleaser-and-github-actions-e08c078e4d0f
- [x] https://blog.goreleaser.com/goreleaser-and-software-supply-chain-security-e8917b26924b
- [x] https://blog.goreleaser.com/reproducible-build-with-goreleaser-6de2763458a5
- [x] https://blog.goreleaser.com/goreleaser-how-to-distribute-your-binaries-with-homebrew-or-gofish-472e007b7992
- [x] https://blog.goreleaser.com/use-goreleaser-with-azure-devops-c2212d3996ca
- [x] https://blog.goreleaser.com/how-to-use-goreleaser-with-cloud-native-storage-bbc4bee5fe91
- [ ] redirect blog.goreleaser.com to goreleaser.com/blog
- [x] RSS feeds
- [x] check dead links
- [x] change production to python 3.11

### PR DESCRIPTION
**Pull request by caarlos0**
Starting to move the blog from medium to mkdocs!

closes #3503

### CODE REVIEW

**Review by xavidop — CHANGES_REQUESTED** [review]
You will need to add the GA analytics tag to keep the tracking.

you will probably need to exclude these folders from goreleaser so you can post any article without generating a new goreleaser version

**Comment by caarlos0** [comment]
> You will need to add the GA analytics tag to keep the tracking.
> 
> you will probably need to exclude these folders from goreleaser so you can post any article without generating a new goreleaser version

I don't actually care about traffic.

Docs are published from main, so we already don't need to tag 🙏🏻

**Comment by xavidop** [comment]
> > You will need to add the GA analytics tag to keep the tracking.
> > you will probably need to exclude these folders from goreleaser so you can post any article without generating a new goreleaser version
> 
> I don't actually care about traffic.
> 
> Docs are published from main, so we already don't need to tag 🙏🏻

sounds good! thanks for clarifying

**Review by xavidop — CHANGES_REQUESTED** [review]
for the posts, what I would suggest to add the date and then the post name, and also add categories, like new versions, use cases, etc.

Look at mine as an example: https://github.com/xavidop/blog/tree/master/dialogflow/_posts

So when ti grows, it will be easier to find the articles

**Comment by caarlos0** [comment]
categories are already there, so far only one (announcements).

about the file names... I'm not particularly a fan, but I see your point, will do the changes

**Pull request merged**
