### PR TITLE
fix: reject docker.files as . or inside dist

### LINKED ISSUE #1117: 'file name too long' when using '.' as 'extra_files'
**Describe the bug**

I have an existing application which builds Docker images for deployment. I want to use goreleaser to push those Docker images to Docker Hub with appropriate versioned tags. Building those images requires the entire project, not just a single binary. I thought I could do this by adding `.` in the `extra_files` directive under `dockers`. Unfortunately, it seems that goreleaser attempts to first copy everything in `extra_files` under `dist` (why not use an actual temporary directory?), and since `dist` is inside the project directory we get a recursive copy:

```
   • DOCKER IMAGES
   ⨯ release failed after 19.09s error=failed to link extra file '.': link dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/Dockerfile dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/dist/goreleaserdocker464502682/Dockerfile: file name too long
```

I thought that adding `dist` to `.dockerignore` might fix the problem, but no dice as it seems the problem stems from goreleaser and not Docker.

**To Reproduce**

```yaml
dockers:
  - binaries: []
    extra_files:
      - .
    image_templates:
      - test
    skip_push: true
```

> Make sure your config file is valid by running
> `goreleaser check -f path-to-config-file`.

**Expected behavior**

I should be able to build my Docker images the same way that `docker build .` works.

**Environment (please complete the following information):**

- OS: macOS 10.14.6
- OS version: Darwin hostname 18.7.0 Darwin Kernel Version 18.7.0
- GoReleaser Version: 0.114.1 (36b190490f7b1716c9edb9ce96f243397b97abf3)

### PR DESCRIPTION
**Pull request by caarlos0**
prevent setting `docker.files` to `.` or something inside `./dist`, hence not allowing "infinite path loops"

closes #1117

### CODE REVIEW

**Comment by raxod502** [comment]
Does this actually fix the problem #1117? I.e. is it now possible to build a Docker image that requires all of the project files in `.`?

**Comment by caarlos0** [comment]
No, no clean way to fix it right now, you can put all files you need inside another folder and add that instead.

**Comment by raxod502** [comment]
In that case can we keep the issue open since the problem isn't really fixed?

**Comment by caarlos0** [comment]
it will not be fixed, at least not now...

to maybe fix that it would require a lot of refactory on the docker pipe, and adding the entire folder is not very common as goreleaser built docker images are usually just install deps and copy the binary...

**Pull request merged**
