### PR TITLE
fix: improve brew formula

### PR DESCRIPTION
**Pull request by caarlos0**
closes https://github.com/goreleaser/goreleaser/issues/2159

would be amazing if someone can help testing this 🙏

### CODE REVIEW

**Review by mgrachev — APPROVED** [review]
LGTM 👍

**Review by radeksimko — COMMENTED** [review]
This is better than it was, but I reckon that a part of this PR was reverted due to https://github.com/goreleaser/goreleaser/issues/2270 - which is reasonable solution for unblocking people 👍🏻  but it still leaves the main case described as part of the original issue unresolved.

I think that `depends_on :arch` was the right approach, but from what I can tell it evaluates multiple architectures there as "AND", rather than "OR", which then makes it an unsatisfiable condition for any multi-arch builds.

https://github.com/Homebrew/brew/blob/3476ca7b8ff889ef61e65783d35d1b2073bd4012/Library/Homebrew/requirements/arch_requirement.rb#L21-L27

I'm not sure this is actually intended on Homebrew's side, so I'm going to open an issue 🤔

**Comment by radeksimko** [comment]
See https://github.com/Homebrew/discussions/discussions/1595

**Comment by caarlos0** [comment]
yes, I forgot to reopen the issue, thanks for pinging 🙏🏻

**Pull request merged**
