### PR TITLE
feat(winget): update manifest schema version & links

### PR DESCRIPTION
**Pull request by vedantmgoyal2009**
Use the latest schema `1.5.0` available on winget-pkgs.

### CODE REVIEW

**Review by caarlos0 — COMMENTED** [review]
hey, thanks for the PR!

Doesn't this version update change anything on the fields we use? Whats different from 1.4 to 1.5?

**Comment by vedantmgoyal2009** [comment]
As far as I know, no changes have been made to existing fields. Some new fields were introduced though, but they aren't  available for public use in winget-pkgs. I updated it because I think it's good to use latest version.

**Comment by caarlos0** [comment]
gotcha, what effects could this have? people with older winget versions not being able to install things maybe? 

if it can have negative effects, I would probably hold it a little

**Comment by vedantmgoyal2009** [comment]
No negative effects it should have. WinGet is fully backwards compatible:)

**Pull request merged**
