### PR TITLE
feat(notary): allow to sign without notarizing

### LINKED ISSUE #4890: allow to sign without notarizing
see discussion in https://github.com/orgs/goreleaser/discussions/4884

### PR DESCRIPTION
**Pull request by caarlos0**
closes #4890

- [x] docs
- [ ] tests

### CODE REVIEW

**Comment by dehanj** [comment]
You where quicker than me, was about to file a PR with a similar solution.

I tested this by building Goreleaser locally and running the same `goreleaser.yaml` which failed before, [see in discussion](https://github.com/orgs/goreleaser/discussions/4884), and this time it works like a charm.
The signature checks out.

```
  • sign & notarize macOS binaries
    • signing                                        binary=dist/...
    • will not try to notarize                       binary=dist/...
    • took: 1s
```

**Comment by fkorotkov** [comment]
Any plans to release 2.1? Would love to sign only but not notirize.

**Comment by caarlos0** [comment]
not yet, but probably next week or so.

in the meantime you can use the nightly builds if you want to wait.

I just triggered a build, it should be finished in a couple of minutes: https://github.com/goreleaser/goreleaser/actions/runs/9570087466/job/26384063797

**Comment by fkorotkov** [comment]
@caarlos0 much appreciated! Could you also kick a nightly build for the Pro version?

**Comment by caarlos0** [comment]
sure!

**Comment by caarlos0** [comment]
forgot to update here, but its there now:


- https://github.com/goreleaser/goreleaser/releases/tag/nightly
- https://github.com/goreleaser/goreleaser-pro/releases/tag/nightly

**Pull request merged**
