### PR TITLE
feat: add support for scripts in Scoop manifests

### PR DESCRIPTION
**Pull request by suz-stripe**
# If applied, this commit will...

add support for `pre_install` and `post_install` [optional properties](https://scoop-docs.now.sh/docs/concepts/App-Manifests.html#optional-properties) in the generated Scoop app manifest.

# Why is this change being made?

GoReleaser has a good Scoop integration, however there are some gaps in support for certain optional properties in the generated app manifest. Preinstall and postinstall scripts are really handy features to have.

We use GoReleaser to release our CLI. We'd love to be able to perform some checks via pre/post install scripts for an improved Scoop installation experience of our CLI.

Thank you for considering this addition! 🙇‍♀️ 

# Provide links to any relevant tickets, URLs or other resources

If you'd like to verify what preinstall and postinstall scripts look like with Scoop, I made you a [demo repo](https://github.com/suz-stripe/scoop-test) and you can see the Scoop output in a [Github Action log output](https://github.com/suz-stripe/scoop-test/runs/1490247874?check_suite_focus=true#step:3:25) from the same repo.

Let me know if you think the test I added is sufficient. Thank you for this project! 🌻

### CODE REVIEW

**Comment by suz-stripe** [comment]
I seem to have a newline issue in the JSON diff of the test, however I am not sure how to fix this

**Review by caarlos0 — APPROVED** [review]

**Comment by caarlos0** [comment]
There is a test failure, but other that LGTM :)

**Comment by suz-stripe** [comment]
@caarlos0 great thanks! I did some digging yesterday on the test failure and I'm sure it's a golang thing I am not interpreting correctly. Will update you on this shortly after trying again.

**Comment by suz-stripe** [comment]
tests are now passing 🎉

**Comment by caarlos0** [comment]
Awesome, thanks 🚀

**Pull request merged**
