### PR TITLE
chore(deps): bump code.gitea.io/sdk/gitea from v0.12.1 to v0.13.1

### PR DESCRIPTION
**Pull request by 6543**
follow up of  #1806

close #1827

### CODE REVIEW

**Comment by 6543** [comment]
@caarlos0 hope you dont have to revert this one ...

next round ;)

**Comment by 6543** [comment]
ok need more investigation ...

**Comment by 6543** [comment]
@caarlos0 5882140c916dedb240a4de60bbe79a142f4be619 did it

**Review by caarlos0 — APPROVED** [review]

**Comment by caarlos0** [comment]
Awesome, thanks 🙏

**Pull request merged**
