### PR TITLE
allow to overwrite the snap name

### PR DESCRIPTION
**Pull request by elopio**

### CODE REVIEW

**Comment by elopio** [comment]
From your comment in bug #328, I realized that we need to allow to overwrite the `name` in the snap.yaml in case the project name doesn't match with the valid values of the Ubuntu store.

**Comment by caarlos0** [comment]
@elopio the name must be in the format `name_version_arch.snap` or it can anything?

**Comment by elopio** [comment]
@caarlos0 The .snap name can be anything. The `name` in the .yaml needs to be `^[a-z0-9][a-z0-9+-]*$`.

**Comment by caarlos0** [comment]
@elopio got it. We can add the templating in another time :)

**Pull request merged**
