### PR TITLE
feat: add custom_block to brew formula generation

### PR DESCRIPTION
**Pull request by fgsch**
This allow authors to specify things such as devel, head and more.

I'm proposing this change so we can let users run projects from master.

See https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md#advanced-formula-tricks for details.

### CODE REVIEW

**Comment by caarlos0** [comment]
LGTM, can you also add it to `brew.md`?

**Comment by fgsch** [comment]
Sure, I will add it and update this PR.

**Comment by fgsch** [comment]
Doc added and rebased.

**Comment by caarlos0** [comment]
awesome, thanks!

**Pull request merged**
