### PR TITLE
feat: winget support

### PR DESCRIPTION
**Pull request by caarlos0**
this will add support to winget into goreleaser.

Basically, the plan is:

- we generate the 3 needed yaml files 
- we commit them to a repo

and that's it.

Initially, will probably have limited options support, and will only have the default locale.

###### TODO

- [x] docs
- [x] review by someone who knows how this works?
- [x] test install somewhere
- [x] more tests maybe?
- [x] PR templates via API? https://github.com/goreleaser/goreleaser/pull/4105
- [x] real project test 
- [x] setup goreleaser to pr to winget as well
- [x] document sync fork stuff https://github.com/goreleaser/goreleaser/pull/4106

### CODE REVIEW

**Comment by denelon** [comment]
There are a couple of examples you could follow using [wingetcreate](https://github.com/microsoft/winget-create) if you're going to use GitHub actions:
* [PowerToys](https://github.com/microsoft/PowerToys/blob/main/.github/workflows/package-submissions.yml)
* [Oh-My-Posh](https://github.com/JanDeDobbeleer/oh-my-posh)

**Comment by caarlos0** [comment]
> You could also take a look at [YAMLcreate](https://github.com/microsoft/winget-pkgs/blob/master/Tools/YamlCreate.ps1)

why? is there anything wrong with my current implementation?

**Comment by denelon** [comment]
Not at all. 😊

I was just offering additional resources.

Oh, I also noticed you were referring to the 1.5 schema which isn't accepted in the community repository yet. We will wait until ~50% of users are on the latest version before opening up validation for the 1.5 schema. The 1.x versions are "non-breaking" so you should just be able to modify the files to use 1.4.0 and then upgrade after 1.5.0 is stable. I'd expect the first or second week in July.

**Comment by caarlos0** [comment]
image

Installed via generated winget manifest! 🤘

**Comment by caarlos0** [comment]
I don't understand why it complains about the `head` 🤔 

```
carlos@darkstar Developer/goreleaser/goreleaser on  winget !
❯ curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/microsoft/winget-pkgs/pulls \
          -d '{"title":"test curl","head":"caarlos0-graveyard:winget-pkgs:test-1.0.19","base":"master"}'
{
  "message": "Validation Failed",
  "errors": [
    {
      "resource": "PullRequest",
      "field": "head",
      "code": "invalid"
    }
  ],
  "documentation_url": "https://docs.github.com/rest/reference/pulls#create-a-pull-request"
}

```

**Comment by caarlos0** [comment]
ah, apparently you can't pr to a fork via go-github 🤔

**Pull request merged**
